import { subDays, subHours, subMinutes } from 'date-fns';
import { type Protocol } from '@/lib/types';

export const protocols: Protocol[] = [
  {
    id: '1',
    number: 'PROT-2024-00123',
    project: 'Nova Sede Administrativa',
    interestedParty: 'Diretoria de Engenharia',
    status: 'Em Andamento',
    documentCount: 5,
    lastUpdated: subHours(new Date(), 2).toISOString(),
  },
  {
    id: '2',
    number: 'PROT-2024-00122',
    project: 'Aquisição de Equipamentos',
    interestedParty: 'Departamento de TI',
    status: 'Concluído',
    documentCount: 12,
    lastUpdated: subDays(new Date(), 3).toISOString(),
  },
  {
    id: '3',
    number: 'PROT-2024-00121',
    project: 'Contratação de Terceirizados',
    interestedParty: 'Recursos Humanos',
    status: 'Pendente',
    documentCount: 0,
    lastUpdated: subDays(new Date(), 1).toISOString(),
  },
  {
    id: '4',
    number: 'PROT-2024-00120',
    project: 'Revisão Orçamentária Q3',
    interestedParty: 'Financeiro',
    status: 'Em Andamento',
    documentCount: 2,
    lastUpdated: subMinutes(new Date(), 45).toISOString(),
  },
  {
    id: '5',
    number: 'PROT-2023-08991',
    project: 'Campanha de Marketing de Fim de Ano',
    interestedParty: 'Marketing',
    status: 'Cancelado',
    documentCount: 8,
    lastUpdated: subDays(new Date(), 90).toISOString(),
  },
  {
    id: '6',
    number: 'PROT-2024-00119',
    project: 'Certificação ISO 9001',
    interestedParty: 'Qualidade',
    status: 'Concluído',
    documentCount: 25,
    lastUpdated: subDays(new Date(), 15).toISOString(),
  },
  {
    id: '7',
    number: 'PROT-2024-00118',
    project: 'Desenvolvimento de App Interno',
    interestedParty: 'Departamento de TI',
    status: 'Em Andamento',
    documentCount: 3,
    lastUpdated: subDays(new Date(), 2).toISOString(),
  },
    {
    id: '8',
    number: 'PROT-2024-00117',
    project: 'Auditoria de Segurança',
    interestedParty: 'Segurança da Informação',
    status: 'Pendente',
    documentCount: 1,
    lastUpdated: subDays(new Date(), 7).toISOString(),
  },
  {
    id: '9',
    number: 'PROT-2024-00116',
    project: 'Plano de Expansão SP',
    interestedParty: 'Diretoria Executiva',
    status: 'Em Andamento',
    documentCount: 1,
    lastUpdated: subHours(new Date(), 8).toISOString(),
  },
  {
    id: '10',
    number: 'PROT-2024-00115',
    project: 'Relatório de Sustentabilidade',
    interestedParty: 'ESG',
    status: 'Concluído',
    documentCount: 4,
    lastUpdated: subDays(new Date(), 22).toISOString(),
  },
  {
    id: '11',
    number: 'PROT-2024-00114',
    project: 'Manutenção Preventiva',
    interestedParty: 'Infraestrutura',
    status: 'Pendente',
    documentCount: 0,
    lastUpdated: subDays(new Date(), 5).toISOString(),
  },
];
