import { subDays, subHours, subMinutes } from 'date-fns';
import type { ProtocoloInterno, TramitacaoInterna } from './types';

// ============================================
// Protocolos internos mock (criados pelo GED)
// ============================================

export const mockProtocolosInternos: ProtocoloInterno[] = [
  {
    id: 'gpi_1',
    numero: 'GED-2026-001',
    assunto: 'Solicitação de compra de material de escritório',
    descricao: 'Necessidade urgente de papelaria para o setor administrativo: resmas de papel A4, canetas, grampeadores e pastas.',
    status: 'EM_ANDAMENTO',
    setorOrigem: 'Gerência Administrativa',
    criadoPorEmail: 'carlos@fadex.org.br',
    criadoPorNome: 'Carlos Mendes',
    criadoEm: subDays(new Date(), 12).toISOString(),
    atualizadoEm: subDays(new Date(), 2).toISOString(),
  },
  {
    id: 'gpi_2',
    numero: 'GED-2026-002',
    assunto: 'Requisição de manutenção predial — ar condicionado',
    descricao: 'O ar condicionado da sala de reuniões do 2º andar está com defeito. Necessário acionar manutenção.',
    status: 'FINALIZADO',
    setorOrigem: 'Gerência de Projetos',
    criadoPorEmail: 'ana@fadex.org.br',
    criadoPorNome: 'Ana Silva',
    criadoEm: subDays(new Date(), 20).toISOString(),
    atualizadoEm: subDays(new Date(), 8).toISOString(),
  },
  {
    id: 'gpi_3',
    numero: 'GED-2026-003',
    assunto: 'Solicitação de acesso ao sistema SAGI para novo colaborador',
    descricao: 'Solicitar criação de usuário no SAGI para o novo analista do setor financeiro, João Pereira.',
    status: 'ABERTO',
    setorOrigem: 'Gerência Financeira',
    criadoPorEmail: 'mariana@fadex.org.br',
    criadoPorNome: 'Mariana Costa',
    criadoEm: subHours(new Date(), 5).toISOString(),
    atualizadoEm: subHours(new Date(), 5).toISOString(),
  },
  {
    id: 'gpi_4',
    numero: 'GED-2026-004',
    assunto: 'Encaminhamento de parecer jurídico — Contrato UFPI',
    descricao: 'Parecer sobre cláusulas do novo contrato de prestação de serviços com a UFPI, referente ao projeto PROPESQI.',
    status: 'EM_ANDAMENTO',
    setorOrigem: 'Jurídico',
    criadoPorEmail: 'roberto@fadex.org.br',
    criadoPorNome: 'Roberto Alves',
    criadoEm: subDays(new Date(), 7).toISOString(),
    atualizadoEm: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 'gpi_5',
    numero: 'GED-2026-005',
    assunto: 'Devolução de equipamento — notebook Dell Latitude',
    descricao: 'Devolução de notebook patrimonial pela ex-bolsista Maria Fernanda ao setor de Patrimônio.',
    status: 'FINALIZADO',
    setorOrigem: 'Gerência de Projetos',
    criadoPorEmail: 'ana@fadex.org.br',
    criadoPorNome: 'Ana Silva',
    criadoEm: subDays(new Date(), 30).toISOString(),
    atualizadoEm: subDays(new Date(), 22).toISOString(),
  },
  {
    id: 'gpi_6',
    numero: 'GED-2026-006',
    assunto: 'Solicitação de diárias — viagem Brasília',
    descricao: 'Solicitação de diárias para participação em reunião no MEC nos dias 15 e 16 de março.',
    status: 'CANCELADO',
    setorOrigem: 'Superintendência',
    criadoPorEmail: 'lucas@fadex.org.br',
    criadoPorNome: 'Lucas Oliveira',
    criadoEm: subDays(new Date(), 15).toISOString(),
    atualizadoEm: subDays(new Date(), 10).toISOString(),
  },
  {
    id: 'gpi_7',
    numero: 'GED-2026-007',
    assunto: 'Pedido de cotação — serviço de impressão',
    descricao: 'Necessário solicitar cotação de 3 fornecedores para serviço de impressão de relatórios anuais.',
    status: 'EM_ANDAMENTO',
    setorOrigem: 'Compras e Licitações',
    criadoPorEmail: 'patricia@fadex.org.br',
    criadoPorNome: 'Patrícia Lima',
    criadoEm: subDays(new Date(), 4).toISOString(),
    atualizadoEm: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 'gpi_8',
    numero: 'GED-2026-008',
    assunto: 'Comunicado interno — horário de funcionamento Carnaval',
    descricao: null,
    status: 'FINALIZADO',
    setorOrigem: 'Recursos Humanos',
    criadoPorEmail: 'fernanda@fadex.org.br',
    criadoPorNome: 'Fernanda Souza',
    criadoEm: subDays(new Date(), 25).toISOString(),
    atualizadoEm: subDays(new Date(), 20).toISOString(),
  },
  {
    id: 'gpi_9',
    numero: 'GED-2026-009',
    assunto: 'Registro de entrada de material no almoxarifado',
    descricao: 'Registro de entrada de 50 resmas de papel A4, 20 caixas de caneta e material de limpeza recebidos em 20/02.',
    status: 'ABERTO',
    setorOrigem: 'Almoxarifado',
    criadoPorEmail: 'jose@fadex.org.br',
    criadoPorNome: 'José Santos',
    criadoEm: subHours(new Date(), 12).toISOString(),
    atualizadoEm: subHours(new Date(), 12).toISOString(),
  },
  {
    id: 'gpi_10',
    numero: 'GED-2026-010',
    assunto: 'Solicitação de backup dos dados do projeto UFPI/2025',
    descricao: 'Necessário realizar backup completo dos documentos do projeto antes do encerramento formal.',
    status: 'EM_ANDAMENTO',
    setorOrigem: 'Gerência de TI',
    criadoPorEmail: 'vinicius@fadex.org.br',
    criadoPorNome: 'Vinicius Silva',
    criadoEm: subDays(new Date(), 3).toISOString(),
    atualizadoEm: subMinutes(new Date(), 90).toISOString(),
  },
  {
    id: 'gpi_11',
    numero: 'GED-2026-011',
    assunto: 'Conferência de certidões negativas — renovação credenciamento',
    descricao: 'Verificar validade de todas as certidões exigidas para renovação do credenciamento MEC.',
    status: 'ABERTO',
    setorOrigem: 'Contabilidade',
    criadoPorEmail: 'rafael@fadex.org.br',
    criadoPorNome: 'Rafael Barbosa',
    criadoEm: subHours(new Date(), 2).toISOString(),
    atualizadoEm: subHours(new Date(), 2).toISOString(),
  },
  {
    id: 'gpi_12',
    numero: 'GED-2026-012',
    assunto: 'Encaminhamento de nota fiscal para pagamento',
    descricao: 'NF nº 4521 do fornecedor Alpha Papelaria, valor R$ 2.340,00, referente à compra de material.',
    status: 'EM_ANDAMENTO',
    setorOrigem: 'Gerência Administrativa',
    criadoPorEmail: 'carlos@fadex.org.br',
    criadoPorNome: 'Carlos Mendes',
    criadoEm: subDays(new Date(), 2).toISOString(),
    atualizadoEm: subHours(new Date(), 6).toISOString(),
  },
  {
    id: 'gpi_13',
    numero: 'GED-2026-013',
    assunto: 'Relatório mensal de patrimônio — Janeiro 2026',
    descricao: 'Consolidação do inventário patrimonial referente ao mês de janeiro de 2026.',
    status: 'FINALIZADO',
    setorOrigem: 'Patrimônio',
    criadoPorEmail: 'marcos@fadex.org.br',
    criadoPorNome: 'Marcos Vieira',
    criadoEm: subDays(new Date(), 18).toISOString(),
    atualizadoEm: subDays(new Date(), 12).toISOString(),
  },
  {
    id: 'gpi_14',
    numero: 'GED-2026-014',
    assunto: 'Abertura de processo de contratação — desenvolvedor júnior',
    descricao: 'Iniciar processo seletivo para contratação de desenvolvedor júnior para o setor de TI.',
    status: 'ABERTO',
    setorOrigem: 'Recursos Humanos',
    criadoPorEmail: 'fernanda@fadex.org.br',
    criadoPorNome: 'Fernanda Souza',
    criadoEm: subMinutes(new Date(), 45).toISOString(),
    atualizadoEm: subMinutes(new Date(), 45).toISOString(),
  },
  {
    id: 'gpi_15',
    numero: 'GED-2026-015',
    assunto: 'Solicitação de empenho — Projeto IFPI/2026',
    descricao: 'Empenhar valor de R$ 15.000,00 na rubrica 33.90.30 para aquisição de material de consumo.',
    status: 'EM_ANDAMENTO',
    setorOrigem: 'Gerência de Projetos',
    criadoPorEmail: 'ana@fadex.org.br',
    criadoPorNome: 'Ana Silva',
    criadoEm: subDays(new Date(), 1).toISOString(),
    atualizadoEm: subHours(new Date(), 3).toISOString(),
  },
];

// ============================================
// Tramitações internas mock
// ============================================

export const mockTramitacoesInternas: TramitacaoInterna[] = [
  // GPI_1 — Compra de material (3 movimentações)
  {
    id: 'tri_1',
    protocoloInternoId: 'gpi_1',
    deSetor: 'Gerência Administrativa',
    paraSetor: 'Compras e Licitações',
    despacho: 'Solicitar cotação de pelo menos 3 fornecedores para os itens listados.',
    tramitadoPorEmail: 'carlos@fadex.org.br',
    tramitadoPorNome: 'Carlos Mendes',
    tramitadoEm: subDays(new Date(), 11).toISOString(),
  },
  {
    id: 'tri_2',
    protocoloInternoId: 'gpi_1',
    deSetor: 'Compras e Licitações',
    paraSetor: 'Gerência Financeira',
    despacho: 'Cotações anexadas. Menor preço: Alpha Papelaria (R$ 2.340,00). Encaminho para verificação de saldo.',
    tramitadoPorEmail: 'patricia@fadex.org.br',
    tramitadoPorNome: 'Patrícia Lima',
    tramitadoEm: subDays(new Date(), 8).toISOString(),
  },
  {
    id: 'tri_3',
    protocoloInternoId: 'gpi_1',
    deSetor: 'Gerência Financeira',
    paraSetor: 'Diretoria Executiva',
    despacho: 'Saldo disponível na rubrica 33.90.30. Encaminho para autorização.',
    tramitadoPorEmail: 'mariana@fadex.org.br',
    tramitadoPorNome: 'Mariana Costa',
    tramitadoEm: subDays(new Date(), 2).toISOString(),
  },

  // GPI_2 — Manutenção predial (4 movimentações, finalizado)
  {
    id: 'tri_4',
    protocoloInternoId: 'gpi_2',
    deSetor: 'Gerência de Projetos',
    paraSetor: 'Gerência Administrativa',
    despacho: 'Ar condicionado da sala de reuniões não liga. Solicito providências.',
    tramitadoPorEmail: 'ana@fadex.org.br',
    tramitadoPorNome: 'Ana Silva',
    tramitadoEm: subDays(new Date(), 19).toISOString(),
  },
  {
    id: 'tri_5',
    protocoloInternoId: 'gpi_2',
    deSetor: 'Gerência Administrativa',
    paraSetor: 'Compras e Licitações',
    despacho: 'Solicitar orçamento de empresa de manutenção.',
    tramitadoPorEmail: 'carlos@fadex.org.br',
    tramitadoPorNome: 'Carlos Mendes',
    tramitadoEm: subDays(new Date(), 17).toISOString(),
  },
  {
    id: 'tri_6',
    protocoloInternoId: 'gpi_2',
    deSetor: 'Compras e Licitações',
    paraSetor: 'Gerência Administrativa',
    despacho: 'Serviço contratado com Refrigeração Total. Manutenção agendada para 18/02.',
    tramitadoPorEmail: 'patricia@fadex.org.br',
    tramitadoPorNome: 'Patrícia Lima',
    tramitadoEm: subDays(new Date(), 12).toISOString(),
  },
  {
    id: 'tri_7',
    protocoloInternoId: 'gpi_2',
    deSetor: 'Gerência Administrativa',
    paraSetor: 'Gerência de Projetos',
    despacho: 'Manutenção realizada com sucesso. Equipamento em funcionamento.',
    tramitadoPorEmail: 'carlos@fadex.org.br',
    tramitadoPorNome: 'Carlos Mendes',
    tramitadoEm: subDays(new Date(), 8).toISOString(),
  },

  // GPI_4 — Parecer jurídico (2 movimentações)
  {
    id: 'tri_8',
    protocoloInternoId: 'gpi_4',
    deSetor: 'Jurídico',
    paraSetor: 'Gerência de Projetos',
    despacho: 'Parecer favorável com ressalvas. Sugiro alteração da cláusula 5.2 sobre prazo de vigência.',
    tramitadoPorEmail: 'roberto@fadex.org.br',
    tramitadoPorNome: 'Roberto Alves',
    tramitadoEm: subDays(new Date(), 5).toISOString(),
  },
  {
    id: 'tri_9',
    protocoloInternoId: 'gpi_4',
    deSetor: 'Gerência de Projetos',
    paraSetor: 'Superintendência',
    despacho: 'Cláusula ajustada conforme parecer. Encaminho para ciência e assinatura.',
    tramitadoPorEmail: 'ana@fadex.org.br',
    tramitadoPorNome: 'Ana Silva',
    tramitadoEm: subDays(new Date(), 1).toISOString(),
  },

  // GPI_5 — Devolução equipamento (2 movimentações, finalizado)
  {
    id: 'tri_10',
    protocoloInternoId: 'gpi_5',
    deSetor: 'Gerência de Projetos',
    paraSetor: 'Patrimônio',
    despacho: 'Notebook Dell Latitude, patrimônio nº 5432, devolvido pela bolsista.',
    tramitadoPorEmail: 'ana@fadex.org.br',
    tramitadoPorNome: 'Ana Silva',
    tramitadoEm: subDays(new Date(), 28).toISOString(),
  },
  {
    id: 'tri_11',
    protocoloInternoId: 'gpi_5',
    deSetor: 'Patrimônio',
    paraSetor: 'Gerência de Projetos',
    despacho: 'Equipamento conferido e reintegrado ao patrimônio. Termo de devolução assinado.',
    tramitadoPorEmail: 'marcos@fadex.org.br',
    tramitadoPorNome: 'Marcos Vieira',
    tramitadoEm: subDays(new Date(), 22).toISOString(),
  },

  // GPI_7 — Cotação impressão (1 movimentação)
  {
    id: 'tri_12',
    protocoloInternoId: 'gpi_7',
    deSetor: 'Compras e Licitações',
    paraSetor: 'Gerência Financeira',
    despacho: 'Cotações recebidas. Menor preço: Gráfica Express (R$ 4.800,00). Solicito verificação de rubrica.',
    tramitadoPorEmail: 'patricia@fadex.org.br',
    tramitadoPorNome: 'Patrícia Lima',
    tramitadoEm: subDays(new Date(), 1).toISOString(),
  },

  // GPI_10 — Backup TI (2 movimentações)
  {
    id: 'tri_13',
    protocoloInternoId: 'gpi_10',
    deSetor: 'Gerência de TI',
    paraSetor: 'Gerência de Projetos',
    despacho: 'Solicitar listagem dos documentos essenciais do projeto UFPI/2025 para inclusão no backup.',
    tramitadoPorEmail: 'vinicius@fadex.org.br',
    tramitadoPorNome: 'Vinicius Silva',
    tramitadoEm: subDays(new Date(), 2).toISOString(),
  },
  {
    id: 'tri_14',
    protocoloInternoId: 'gpi_10',
    deSetor: 'Gerência de Projetos',
    paraSetor: 'Gerência de TI',
    despacho: 'Listagem anexada. Incluir também os relatórios de prestação de contas parciais.',
    tramitadoPorEmail: 'ana@fadex.org.br',
    tramitadoPorNome: 'Ana Silva',
    tramitadoEm: subMinutes(new Date(), 90).toISOString(),
  },

  // GPI_12 — NF para pagamento (2 movimentações)
  {
    id: 'tri_15',
    protocoloInternoId: 'gpi_12',
    deSetor: 'Gerência Administrativa',
    paraSetor: 'Gerência Financeira',
    despacho: 'NF nº 4521 — Alpha Papelaria. Valor: R$ 2.340,00. Solicito empenho e pagamento.',
    tramitadoPorEmail: 'carlos@fadex.org.br',
    tramitadoPorNome: 'Carlos Mendes',
    tramitadoEm: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 'tri_16',
    protocoloInternoId: 'gpi_12',
    deSetor: 'Gerência Financeira',
    paraSetor: 'Contabilidade',
    despacho: 'Empenho realizado. Encaminho para lançamento contábil e agendamento de pagamento.',
    tramitadoPorEmail: 'mariana@fadex.org.br',
    tramitadoPorNome: 'Mariana Costa',
    tramitadoEm: subHours(new Date(), 6).toISOString(),
  },

  // GPI_13 — Relatório patrimônio (2 movimentações, finalizado)
  {
    id: 'tri_17',
    protocoloInternoId: 'gpi_13',
    deSetor: 'Patrimônio',
    paraSetor: 'Contabilidade',
    despacho: 'Relatório mensal de patrimônio Janeiro/2026 consolidado. Encaminho para conferência.',
    tramitadoPorEmail: 'marcos@fadex.org.br',
    tramitadoPorNome: 'Marcos Vieira',
    tramitadoEm: subDays(new Date(), 16).toISOString(),
  },
  {
    id: 'tri_18',
    protocoloInternoId: 'gpi_13',
    deSetor: 'Contabilidade',
    paraSetor: 'Patrimônio',
    despacho: 'Conferido e aprovado. Sem divergências.',
    tramitadoPorEmail: 'rafael@fadex.org.br',
    tramitadoPorNome: 'Rafael Barbosa',
    tramitadoEm: subDays(new Date(), 12).toISOString(),
  },

  // GPI_15 — Empenho projeto IFPI (1 movimentação)
  {
    id: 'tri_19',
    protocoloInternoId: 'gpi_15',
    deSetor: 'Gerência de Projetos',
    paraSetor: 'Gerência Financeira',
    despacho: 'Solicitar empenho de R$ 15.000,00 na rubrica 33.90.30 do projeto IFPI/2026.',
    tramitadoPorEmail: 'ana@fadex.org.br',
    tramitadoPorNome: 'Ana Silva',
    tramitadoEm: subHours(new Date(), 3).toISOString(),
  },
];

export function getProtocoloInternoById(id: string): ProtocoloInterno | undefined {
  return mockProtocolosInternos.find((p) => p.id === id);
}

export function getTramitacoesByProtocoloInterno(protocoloInternoId: string): TramitacaoInterna[] {
  return mockTramitacoesInternas
    .filter((t) => t.protocoloInternoId === protocoloInternoId)
    .sort((a, b) => new Date(a.tramitadoEm).getTime() - new Date(b.tramitadoEm).getTime());
}
