import type { AdminUser, ActivityLog } from './types';

export const mockAdmins: AdminUser[] = [
  {
    id: 'adm_1',
    nome: 'Suporte TI',
    email: 'suporteti@fadex.org.br',
    setor: 'Gerência de TI',
    gedRole: 'super_admin',
    ativo: true,
    adicionadoEm: '2025-01-15T10:00:00Z',
    adicionadoPor: 'Sistema',
  },
  {
    id: 'adm_2',
    nome: 'Maria Oliveira',
    email: 'maria.oliveira@fadex.org.br',
    setor: 'Gerência de Projetos',
    gedRole: 'admin',
    ativo: true,
    adicionadoEm: '2025-02-01T14:30:00Z',
    adicionadoPor: 'suporteti@fadex.org.br',
  },
  {
    id: 'adm_3',
    nome: 'Carlos Santos',
    email: 'carlos.santos@fadex.org.br',
    setor: 'Diretoria Executiva',
    gedRole: 'admin',
    ativo: true,
    adicionadoEm: '2025-03-10T09:15:00Z',
    adicionadoPor: 'suporteti@fadex.org.br',
  },
  {
    id: 'adm_4',
    nome: 'Ana Costa',
    email: 'ana.costa@fadex.org.br',
    setor: 'Gerência Financeira',
    gedRole: 'admin',
    ativo: true,
    adicionadoEm: '2025-04-05T11:20:00Z',
    adicionadoPor: 'suporteti@fadex.org.br',
  },
  {
    id: 'adm_5',
    nome: 'Pedro Lima',
    email: 'pedro.lima@fadex.org.br',
    setor: 'Gerência de TI',
    gedRole: 'admin',
    ativo: false,
    adicionadoEm: '2025-02-20T16:45:00Z',
    adicionadoPor: 'suporteti@fadex.org.br',
  },
];

export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'log_1',
    acao: 'UPLOAD',
    descricao: 'Upload de documento "Ofício 234/2025" no protocolo 1234/2025',
    usuarioNome: 'Maria Oliveira',
    usuarioEmail: 'maria.oliveira@fadex.org.br',
    setor: 'Gerência de Projetos',
    recurso: 'documento',
    recursoId: 'doc_abc123',
    detalhes: { arquivo: 'oficio-234-2025.pdf', tamanho: '2.4 MB' },
    ip: '192.168.1.50',
    criadoEm: '2026-02-27T14:30:00Z',
  },
  {
    id: 'log_2',
    acao: 'TRAMITAR',
    descricao: 'Protocolo 1234/2025 tramitado de "Gerência de Projetos" para "Diretoria Executiva"',
    usuarioNome: 'Maria Oliveira',
    usuarioEmail: 'maria.oliveira@fadex.org.br',
    setor: 'Gerência de Projetos',
    recurso: 'protocolo',
    recursoId: '1234/2025',
    detalhes: { de: 'Gerência de Projetos', para: 'Diretoria Executiva' },
    ip: '192.168.1.50',
    criadoEm: '2026-02-27T14:15:00Z',
  },
  {
    id: 'log_3',
    acao: 'LOGIN',
    descricao: 'Login realizado com sucesso',
    usuarioNome: 'Suporte TI',
    usuarioEmail: 'suporteti@fadex.org.br',
    setor: 'Gerência de TI',
    recurso: null,
    recursoId: null,
    detalhes: null,
    ip: '192.168.1.10',
    criadoEm: '2026-02-27T13:00:00Z',
  },
  {
    id: 'log_4',
    acao: 'DELETE',
    descricao: 'Documento "Nota Fiscal 567.pdf" removido do protocolo 890/2025',
    usuarioNome: 'Carlos Santos',
    usuarioEmail: 'carlos.santos@fadex.org.br',
    setor: 'Diretoria Executiva',
    recurso: 'documento',
    recursoId: 'doc_def456',
    detalhes: { motivo: 'Arquivo duplicado' },
    ip: '192.168.1.30',
    criadoEm: '2026-02-27T11:45:00Z',
  },
  {
    id: 'log_5',
    acao: 'ADMIN_CHANGE',
    descricao: 'Administrador "Ana Costa" adicionado ao sistema',
    usuarioNome: 'Suporte TI',
    usuarioEmail: 'suporteti@fadex.org.br',
    setor: 'Gerência de TI',
    recurso: 'admin',
    recursoId: 'adm_4',
    detalhes: { email: 'ana.costa@fadex.org.br', role: 'admin' },
    ip: '192.168.1.10',
    criadoEm: '2026-02-27T10:30:00Z',
  },
  {
    id: 'log_6',
    acao: 'CREATE',
    descricao: 'Protocolo interno PI-2026/003 criado',
    usuarioNome: 'Ana Costa',
    usuarioEmail: 'ana.costa@fadex.org.br',
    setor: 'Gerência Financeira',
    recurso: 'protocolo_interno',
    recursoId: 'pi_003',
    detalhes: { assunto: 'Requisição de material' },
    ip: '192.168.1.40',
    criadoEm: '2026-02-27T09:20:00Z',
  },
  {
    id: 'log_7',
    acao: 'EDIT',
    descricao: 'Tipo de documento "Contrato" atualizado',
    usuarioNome: 'Suporte TI',
    usuarioEmail: 'suporteti@fadex.org.br',
    setor: 'Gerência de TI',
    recurso: 'tipo_documento',
    recursoId: 'td_2',
    detalhes: { campo: 'descrição' },
    ip: '192.168.1.10',
    criadoEm: '2026-02-26T16:00:00Z',
  },
  {
    id: 'log_8',
    acao: 'EXPORT',
    descricao: 'Dossiê do protocolo 456/2025 exportado em PDF',
    usuarioNome: 'Pedro Lima',
    usuarioEmail: 'pedro.lima@fadex.org.br',
    setor: 'Gerência de TI',
    recurso: 'protocolo',
    recursoId: '456/2025',
    detalhes: { formato: 'PDF', paginas: '12' },
    ip: '192.168.1.60',
    criadoEm: '2026-02-26T14:30:00Z',
  },
  {
    id: 'log_9',
    acao: 'UPLOAD',
    descricao: 'Upload de 3 documentos no protocolo 789/2025',
    usuarioNome: 'Carlos Santos',
    usuarioEmail: 'carlos.santos@fadex.org.br',
    setor: 'Diretoria Executiva',
    recurso: 'documento',
    recursoId: '789/2025',
    detalhes: { quantidade: '3', tamanhoTotal: '8.7 MB' },
    ip: '192.168.1.30',
    criadoEm: '2026-02-26T11:15:00Z',
  },
  {
    id: 'log_10',
    acao: 'LOGIN',
    descricao: 'Login realizado com sucesso',
    usuarioNome: 'Maria Oliveira',
    usuarioEmail: 'maria.oliveira@fadex.org.br',
    setor: 'Gerência de Projetos',
    recurso: null,
    recursoId: null,
    detalhes: null,
    ip: '192.168.1.50',
    criadoEm: '2026-02-26T08:00:00Z',
  },
  {
    id: 'log_11',
    acao: 'TRAMITAR',
    descricao: 'Protocolo 567/2025 tramitado de "Gerência Financeira" para "Superintendência"',
    usuarioNome: 'Ana Costa',
    usuarioEmail: 'ana.costa@fadex.org.br',
    setor: 'Gerência Financeira',
    recurso: 'protocolo',
    recursoId: '567/2025',
    detalhes: { de: 'Gerência Financeira', para: 'Superintendência' },
    ip: '192.168.1.40',
    criadoEm: '2026-02-25T15:45:00Z',
  },
  {
    id: 'log_12',
    acao: 'DELETE',
    descricao: 'Observação removida do protocolo 234/2025',
    usuarioNome: 'Suporte TI',
    usuarioEmail: 'suporteti@fadex.org.br',
    setor: 'Gerência de TI',
    recurso: 'observacao',
    recursoId: 'obs_789',
    detalhes: { motivo: 'Conteúdo incorreto' },
    ip: '192.168.1.10',
    criadoEm: '2026-02-25T10:30:00Z',
  },
  {
    id: 'log_13',
    acao: 'UPLOAD',
    descricao: 'Upload de documento "Relatório Mensal.pdf" no protocolo 123/2025',
    usuarioNome: 'Pedro Lima',
    usuarioEmail: 'pedro.lima@fadex.org.br',
    setor: 'Gerência de TI',
    recurso: 'documento',
    recursoId: 'doc_ghi789',
    detalhes: { arquivo: 'relatorio-mensal.pdf', tamanho: '5.1 MB' },
    ip: '192.168.1.60',
    criadoEm: '2026-02-25T09:00:00Z',
  },
  {
    id: 'log_14',
    acao: 'ADMIN_CHANGE',
    descricao: 'Administrador "Pedro Lima" desativado',
    usuarioNome: 'Suporte TI',
    usuarioEmail: 'suporteti@fadex.org.br',
    setor: 'Gerência de TI',
    recurso: 'admin',
    recursoId: 'adm_5',
    detalhes: { email: 'pedro.lima@fadex.org.br', acao: 'desativado' },
    ip: '192.168.1.10',
    criadoEm: '2026-02-24T16:30:00Z',
  },
  {
    id: 'log_15',
    acao: 'CREATE',
    descricao: 'Tipo de documento "Ata de Reunião" criado',
    usuarioNome: 'Suporte TI',
    usuarioEmail: 'suporteti@fadex.org.br',
    setor: 'Gerência de TI',
    recurso: 'tipo_documento',
    recursoId: 'td_8',
    detalhes: null,
    ip: '192.168.1.10',
    criadoEm: '2026-02-24T14:00:00Z',
  },
];
