import { subDays, subHours } from 'date-fns';
import type { Documento } from './types';

export const mockDocumentos: Documento[] = [
  // Protocolo 1523/2026 — 5 docs
  {
    id: 'doc_1',
    protocoloSagi: '1523/2026',
    tipoDocumentoId: 'dt_1',
    tipoDocumentoNome: 'Ofício',
    nomeArquivo: 'oficio_empenho_001.pdf',
    driveFileId: 'drive_abc001',
    driveFileUrl: 'https://drive.google.com/file/d/drive_abc001',
    tamanhoBytes: 245000,
    mimeType: 'application/pdf',
    uploadedBy: 'luanna@fadex.org.br',
    uploadedAt: subHours(new Date(), 3).toISOString(),
  },
  {
    id: 'doc_2',
    protocoloSagi: '1523/2026',
    tipoDocumentoId: 'dt_5',
    tipoDocumentoNome: 'Relatório',
    nomeArquivo: 'relatorio_financeiro_jan2026.xlsx',
    driveFileId: 'drive_abc002',
    driveFileUrl: 'https://drive.google.com/file/d/drive_abc002',
    tamanhoBytes: 1580000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    uploadedBy: 'milena@fadex.org.br',
    uploadedAt: subHours(new Date(), 5).toISOString(),
  },
  {
    id: 'doc_3',
    protocoloSagi: '1523/2026',
    tipoDocumentoId: 'dt_4',
    tipoDocumentoNome: 'Nota Fiscal',
    nomeArquivo: 'nf_0012345.pdf',
    driveFileId: 'drive_abc003',
    driveFileUrl: 'https://drive.google.com/file/d/drive_abc003',
    tamanhoBytes: 89000,
    mimeType: 'application/pdf',
    uploadedBy: 'reinaldo@fadex.org.br',
    uploadedAt: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 'doc_4',
    protocoloSagi: '1523/2026',
    tipoDocumentoId: 'dt_3',
    tipoDocumentoNome: 'Contrato',
    nomeArquivo: 'contrato_fornecedor_abc.pdf',
    driveFileId: 'drive_abc004',
    driveFileUrl: 'https://drive.google.com/file/d/drive_abc004',
    tamanhoBytes: 3200000,
    mimeType: 'application/pdf',
    uploadedBy: 'tawan@fadex.org.br',
    uploadedAt: subDays(new Date(), 2).toISOString(),
  },
  {
    id: 'doc_5',
    protocoloSagi: '1523/2026',
    tipoDocumentoId: null,
    tipoDocumentoNome: null,
    nomeArquivo: 'foto_comprovante.jpg',
    driveFileId: 'drive_abc005',
    driveFileUrl: 'https://drive.google.com/file/d/drive_abc005',
    tamanhoBytes: 520000,
    mimeType: 'image/jpeg',
    uploadedBy: 'vinicius@fadex.org.br',
    uploadedAt: subDays(new Date(), 2).toISOString(),
  },

  // Protocolo 1521/2026 — 3 docs
  {
    id: 'doc_6',
    protocoloSagi: '1521/2026',
    tipoDocumentoId: 'dt_1',
    tipoDocumentoNome: 'Ofício',
    nomeArquivo: 'oficio_contratacao_bolsista.pdf',
    driveFileId: 'drive_def001',
    driveFileUrl: 'https://drive.google.com/file/d/drive_def001',
    tamanhoBytes: 178000,
    mimeType: 'application/pdf',
    uploadedBy: 'bruna@fadex.org.br',
    uploadedAt: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 'doc_7',
    protocoloSagi: '1521/2026',
    tipoDocumentoId: 'dt_2',
    tipoDocumentoNome: 'Memorando',
    nomeArquivo: 'memorando_rh_023.pdf',
    driveFileId: 'drive_def002',
    driveFileUrl: 'https://drive.google.com/file/d/drive_def002',
    tamanhoBytes: 95000,
    mimeType: 'application/pdf',
    uploadedBy: 'pricyla@fadex.org.br',
    uploadedAt: subDays(new Date(), 2).toISOString(),
  },
  {
    id: 'doc_8',
    protocoloSagi: '1521/2026',
    tipoDocumentoId: null,
    tipoDocumentoNome: null,
    nomeArquivo: 'curriculo_candidato.pdf',
    driveFileId: 'drive_def003',
    driveFileUrl: 'https://drive.google.com/file/d/drive_def003',
    tamanhoBytes: 412000,
    mimeType: 'application/pdf',
    uploadedBy: 'bruna@fadex.org.br',
    uploadedAt: subDays(new Date(), 3).toISOString(),
  },

  // Protocolo 1520/2026 — 18 docs (muitos, para testar paginação)
  ...Array.from({ length: 18 }, (_, i) => ({
    id: `doc_pc_${i + 1}`,
    protocoloSagi: '1520/2026',
    tipoDocumentoId: i % 3 === 0 ? 'dt_5' : i % 3 === 1 ? 'dt_4' : 'dt_9',
    tipoDocumentoNome:
      i % 3 === 0
        ? 'Relatório'
        : i % 3 === 1
          ? 'Nota Fiscal'
          : 'Comprovante de Pagamento',
    nomeArquivo: `prestacao_contas_${String(i + 1).padStart(3, '0')}.pdf`,
    driveFileId: `drive_pc_${i + 1}`,
    driveFileUrl: `https://drive.google.com/file/d/drive_pc_${i + 1}`,
    tamanhoBytes: 120000 + i * 35000,
    mimeType: 'application/pdf',
    uploadedBy: i % 2 === 0 ? 'milena@fadex.org.br' : 'nivea@fadex.org.br',
    uploadedAt: subDays(new Date(), 3 + i).toISOString(),
  })),

  // Protocolo 1519/2026 — 7 docs
  {
    id: 'doc_ta_1',
    protocoloSagi: '1519/2026',
    tipoDocumentoId: 'dt_6',
    tipoDocumentoNome: 'Termo Aditivo',
    nomeArquivo: 'termo_aditivo_prorrogacao.pdf',
    driveFileId: 'drive_ta001',
    driveFileUrl: 'https://drive.google.com/file/d/drive_ta001',
    tamanhoBytes: 890000,
    mimeType: 'application/pdf',
    uploadedBy: 'matusala@fadex.org.br',
    uploadedAt: subDays(new Date(), 3).toISOString(),
  },
  {
    id: 'doc_ta_2',
    protocoloSagi: '1519/2026',
    tipoDocumentoId: 'dt_7',
    tipoDocumentoNome: 'Parecer',
    nomeArquivo: 'parecer_juridico_aditivo.pdf',
    driveFileId: 'drive_ta002',
    driveFileUrl: 'https://drive.google.com/file/d/drive_ta002',
    tamanhoBytes: 345000,
    mimeType: 'application/pdf',
    uploadedBy: 'jessica@fadex.org.br',
    uploadedAt: subDays(new Date(), 4).toISOString(),
  },
  {
    id: 'doc_ta_3',
    protocoloSagi: '1519/2026',
    tipoDocumentoId: 'dt_3',
    tipoDocumentoNome: 'Contrato',
    nomeArquivo: 'contrato_original_2025.pdf',
    driveFileId: 'drive_ta003',
    driveFileUrl: 'https://drive.google.com/file/d/drive_ta003',
    tamanhoBytes: 2100000,
    mimeType: 'application/pdf',
    uploadedBy: 'misael@fadex.org.br',
    uploadedAt: subDays(new Date(), 5).toISOString(),
  },
  {
    id: 'doc_ta_4',
    protocoloSagi: '1519/2026',
    tipoDocumentoId: null,
    tipoDocumentoNome: null,
    nomeArquivo: 'planilha_custos_detalhada.xlsx',
    driveFileId: 'drive_ta004',
    driveFileUrl: 'https://drive.google.com/file/d/drive_ta004',
    tamanhoBytes: 780000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    uploadedBy: 'claudiane@fadex.org.br',
    uploadedAt: subDays(new Date(), 5).toISOString(),
  },
  {
    id: 'doc_ta_5',
    protocoloSagi: '1519/2026',
    tipoDocumentoId: 'dt_10',
    tipoDocumentoNome: 'Portaria',
    nomeArquivo: 'portaria_designacao_coordenador.pdf',
    driveFileId: 'drive_ta005',
    driveFileUrl: 'https://drive.google.com/file/d/drive_ta005',
    tamanhoBytes: 156000,
    mimeType: 'application/pdf',
    uploadedBy: 'juliete@fadex.org.br',
    uploadedAt: subDays(new Date(), 6).toISOString(),
  },
  {
    id: 'doc_ta_6',
    protocoloSagi: '1519/2026',
    tipoDocumentoId: null,
    tipoDocumentoNome: null,
    nomeArquivo: 'foto_laboratorio.png',
    driveFileId: 'drive_ta006',
    driveFileUrl: 'https://drive.google.com/file/d/drive_ta006',
    tamanhoBytes: 4200000,
    mimeType: 'image/png',
    uploadedBy: 'vinicius@fadex.org.br',
    uploadedAt: subDays(new Date(), 7).toISOString(),
  },
  {
    id: 'doc_ta_7',
    protocoloSagi: '1519/2026',
    tipoDocumentoId: 'dt_11',
    tipoDocumentoNome: 'Certidão',
    nomeArquivo: 'certidao_negativa_federal.pdf',
    driveFileId: 'drive_ta007',
    driveFileUrl: 'https://drive.google.com/file/d/drive_ta007',
    tamanhoBytes: 67000,
    mimeType: 'application/pdf',
    uploadedBy: 'reinaldo@fadex.org.br',
    uploadedAt: subDays(new Date(), 8).toISOString(),
  },

  // Protocolo 1517/2026 — 4 docs
  {
    id: 'doc_lic_1',
    protocoloSagi: '1517/2026',
    tipoDocumentoId: 'dt_5',
    tipoDocumentoNome: 'Relatório',
    nomeArquivo: 'cotacao_licencas_software.pdf',
    driveFileId: 'drive_lic001',
    driveFileUrl: 'https://drive.google.com/file/d/drive_lic001',
    tamanhoBytes: 310000,
    mimeType: 'application/pdf',
    uploadedBy: 'vinicius@fadex.org.br',
    uploadedAt: subDays(new Date(), 4).toISOString(),
  },
  {
    id: 'doc_lic_2',
    protocoloSagi: '1517/2026',
    tipoDocumentoId: 'dt_4',
    tipoDocumentoNome: 'Nota Fiscal',
    nomeArquivo: 'nf_microsoft_365.pdf',
    driveFileId: 'drive_lic002',
    driveFileUrl: 'https://drive.google.com/file/d/drive_lic002',
    tamanhoBytes: 123000,
    mimeType: 'application/pdf',
    uploadedBy: 'vinicius@fadex.org.br',
    uploadedAt: subDays(new Date(), 5).toISOString(),
  },
  {
    id: 'doc_lic_3',
    protocoloSagi: '1517/2026',
    tipoDocumentoId: 'dt_3',
    tipoDocumentoNome: 'Contrato',
    nomeArquivo: 'contrato_licenciamento.pdf',
    driveFileId: 'drive_lic003',
    driveFileUrl: 'https://drive.google.com/file/d/drive_lic003',
    tamanhoBytes: 1450000,
    mimeType: 'application/pdf',
    uploadedBy: 'tawan@fadex.org.br',
    uploadedAt: subDays(new Date(), 6).toISOString(),
  },
  {
    id: 'doc_lic_4',
    protocoloSagi: '1517/2026',
    tipoDocumentoId: null,
    tipoDocumentoNome: null,
    nomeArquivo: 'screenshot_instalacao.png',
    driveFileId: 'drive_lic004',
    driveFileUrl: 'https://drive.google.com/file/d/drive_lic004',
    tamanhoBytes: 850000,
    mimeType: 'image/png',
    uploadedBy: 'vinicius@fadex.org.br',
    uploadedAt: subDays(new Date(), 6).toISOString(),
  },

  // Protocolo 1510/2026 — 6 docs
  {
    id: 'doc_diaria_1',
    protocoloSagi: '1514/2026',
    tipoDocumentoId: 'dt_1',
    tipoDocumentoNome: 'Ofício',
    nomeArquivo: 'oficio_solicitacao_diarias.pdf',
    driveFileId: 'drive_dia001',
    driveFileUrl: 'https://drive.google.com/file/d/drive_dia001',
    tamanhoBytes: 190000,
    mimeType: 'application/pdf',
    uploadedBy: 'matusala@fadex.org.br',
    uploadedAt: subDays(new Date(), 7).toISOString(),
  },
  {
    id: 'doc_diaria_2',
    protocoloSagi: '1514/2026',
    tipoDocumentoId: 'dt_9',
    tipoDocumentoNome: 'Comprovante de Pagamento',
    nomeArquivo: 'comprovante_transferencia.pdf',
    driveFileId: 'drive_dia002',
    driveFileUrl: 'https://drive.google.com/file/d/drive_dia002',
    tamanhoBytes: 75000,
    mimeType: 'application/pdf',
    uploadedBy: 'milena@fadex.org.br',
    uploadedAt: subDays(new Date(), 8).toISOString(),
  },
  {
    id: 'doc_diaria_3',
    protocoloSagi: '1514/2026',
    tipoDocumentoId: null,
    tipoDocumentoNome: null,
    nomeArquivo: 'passagem_aerea_ida.pdf',
    driveFileId: 'drive_dia003',
    driveFileUrl: 'https://drive.google.com/file/d/drive_dia003',
    tamanhoBytes: 340000,
    mimeType: 'application/pdf',
    uploadedBy: 'matusala@fadex.org.br',
    uploadedAt: subDays(new Date(), 8).toISOString(),
  },
  {
    id: 'doc_diaria_4',
    protocoloSagi: '1514/2026',
    tipoDocumentoId: null,
    tipoDocumentoNome: null,
    nomeArquivo: 'passagem_aerea_volta.pdf',
    driveFileId: 'drive_dia004',
    driveFileUrl: 'https://drive.google.com/file/d/drive_dia004',
    tamanhoBytes: 335000,
    mimeType: 'application/pdf',
    uploadedBy: 'matusala@fadex.org.br',
    uploadedAt: subDays(new Date(), 8).toISOString(),
  },
  {
    id: 'doc_diaria_5',
    protocoloSagi: '1514/2026',
    tipoDocumentoId: 'dt_5',
    tipoDocumentoNome: 'Relatório',
    nomeArquivo: 'relatorio_visita_tecnica.pdf',
    driveFileId: 'drive_dia005',
    driveFileUrl: 'https://drive.google.com/file/d/drive_dia005',
    tamanhoBytes: 1200000,
    mimeType: 'application/pdf',
    uploadedBy: 'misael@fadex.org.br',
    uploadedAt: subDays(new Date(), 9).toISOString(),
  },
  {
    id: 'doc_diaria_6',
    protocoloSagi: '1514/2026',
    tipoDocumentoId: null,
    tipoDocumentoNome: null,
    nomeArquivo: 'fotos_visita.zip',
    driveFileId: 'drive_dia006',
    driveFileUrl: 'https://drive.google.com/file/d/drive_dia006',
    tamanhoBytes: 5100000,
    mimeType: 'application/zip',
    uploadedBy: 'misael@fadex.org.br',
    uploadedAt: subDays(new Date(), 9).toISOString(),
  },
];

/** Retorna documentos de um protocolo específico */
export function getDocumentosByProtocolo(protocoloSagi: string): Documento[] {
  return mockDocumentos.filter((d) => d.protocoloSagi === protocoloSagi);
}
