import { subDays, subHours, subMinutes } from 'date-fns';
import type { Protocol, Setor } from './types';

// ============================================
// Setores mock (baseados na estrutura real da FADEX)
// ============================================

export const mockSetores: Setor[] = [
  { codigo: 1, nome: 'Superintendência' },
  { codigo: 2, nome: 'Diretoria Executiva' },
  { codigo: 3, nome: 'Gerência de Projetos' },
  { codigo: 4, nome: 'Gerência Financeira' },
  { codigo: 5, nome: 'Gerência de TI' },
  { codigo: 6, nome: 'Gerência Administrativa' },
  { codigo: 7, nome: 'Recursos Humanos' },
  { codigo: 8, nome: 'Compras e Licitações' },
  { codigo: 9, nome: 'Contabilidade' },
  { codigo: 10, nome: 'Jurídico' },
  { codigo: 11, nome: 'Patrimônio' },
  { codigo: 12, nome: 'Almoxarifado' },
];

// ============================================
// Protocolos mock (~30 registros realistas)
// ============================================

export const mockProtocols: Protocol[] = [
  {
    id: 'prot_1',
    numeroProtocolo: 1523,
    anoProtocolo: 2026,
    dataProtocolo: subHours(new Date(), 2).toISOString(),
    codigoOrigem: 3,
    setorOrigem: 'Gerência de Projetos',
    codigoDestino: 4,
    setorDestino: 'Gerência Financeira',
    assunto: 'Solicitação de empenho - Projeto UFPI/PROPESQI 2026',
    situacao: 'Em Andamento',
    projetoDescricao: 'Apoio à Pesquisa UFPI 2026',
    numeroConvenio: 'CONV-2026-001',
    documentCount: 5,
    lastUpdated: subHours(new Date(), 2).toISOString(),
  },
  {
    id: 'prot_2',
    numeroProtocolo: 1522,
    anoProtocolo: 2026,
    dataProtocolo: subHours(new Date(), 6).toISOString(),
    codigoOrigem: 5,
    setorOrigem: 'Gerência de TI',
    codigoDestino: 8,
    setorDestino: 'Compras e Licitações',
    assunto: 'Requisição de compra - Equipamentos de rede',
    situacao: 'Pendente',
    projetoDescricao: 'Infraestrutura de TI',
    numeroConvenio: null,
    documentCount: 0,
    lastUpdated: subHours(new Date(), 6).toISOString(),
  },
  {
    id: 'prot_3',
    numeroProtocolo: 1521,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 1).toISOString(),
    codigoOrigem: 7,
    setorOrigem: 'Recursos Humanos',
    codigoDestino: 2,
    setorDestino: 'Diretoria Executiva',
    assunto: 'Contratação de bolsista - Extensão IFPI',
    situacao: 'Em Andamento',
    projetoDescricao: 'Extensão Tecnológica IFPI',
    numeroConvenio: 'CONV-2026-003',
    documentCount: 3,
    lastUpdated: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 'prot_4',
    numeroProtocolo: 1520,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 2).toISOString(),
    codigoOrigem: 4,
    setorOrigem: 'Gerência Financeira',
    codigoDestino: 9,
    setorDestino: 'Contabilidade',
    assunto: 'Prestação de contas parcial - Convênio UFPI 2025',
    situacao: 'Concluído',
    projetoDescricao: 'Apoio à Pesquisa UFPI 2025',
    numeroConvenio: 'CONV-2025-012',
    documentCount: 18,
    lastUpdated: subDays(new Date(), 2).toISOString(),
  },
  {
    id: 'prot_5',
    numeroProtocolo: 1519,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 3).toISOString(),
    codigoOrigem: 1,
    setorOrigem: 'Superintendência',
    codigoDestino: 10,
    setorDestino: 'Jurídico',
    assunto: 'Análise de termo aditivo - Prorrogação de prazo',
    situacao: 'Em Andamento',
    projetoDescricao: 'Laboratório de Biotecnologia',
    numeroConvenio: 'CONV-2025-008',
    documentCount: 7,
    lastUpdated: subDays(new Date(), 3).toISOString(),
  },
  {
    id: 'prot_6',
    numeroProtocolo: 1518,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 3).toISOString(),
    codigoOrigem: 3,
    setorOrigem: 'Gerência de Projetos',
    codigoDestino: 7,
    setorDestino: 'Recursos Humanos',
    assunto: 'Desligamento de bolsista - Término do vínculo',
    situacao: 'Pendente',
    projetoDescricao: 'Capacitação Docente UFDPar',
    numeroConvenio: 'CONV-2025-015',
    documentCount: 2,
    lastUpdated: subDays(new Date(), 3).toISOString(),
  },
  {
    id: 'prot_7',
    numeroProtocolo: 1517,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 4).toISOString(),
    codigoOrigem: 8,
    setorOrigem: 'Compras e Licitações',
    codigoDestino: 5,
    setorDestino: 'Gerência de TI',
    assunto: 'Resultado de cotação - Licenças de software',
    situacao: 'Concluído',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 4,
    lastUpdated: subDays(new Date(), 4).toISOString(),
  },
  {
    id: 'prot_8',
    numeroProtocolo: 1516,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 5).toISOString(),
    codigoOrigem: 6,
    setorOrigem: 'Gerência Administrativa',
    codigoDestino: 11,
    setorDestino: 'Patrimônio',
    assunto: 'Inventário patrimonial 2026 - Bens móveis',
    situacao: 'Em Andamento',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 0,
    lastUpdated: subDays(new Date(), 5).toISOString(),
  },
  {
    id: 'prot_9',
    numeroProtocolo: 1515,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 5).toISOString(),
    codigoOrigem: 5,
    setorOrigem: 'Gerência de TI',
    codigoDestino: 6,
    setorDestino: 'Gerência Administrativa',
    assunto: 'Manutenção preventiva - Datacenter',
    situacao: 'Pendente',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 1,
    lastUpdated: subDays(new Date(), 5).toISOString(),
  },
  {
    id: 'prot_10',
    numeroProtocolo: 1514,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 7).toISOString(),
    codigoOrigem: 3,
    setorOrigem: 'Gerência de Projetos',
    codigoDestino: 4,
    setorDestino: 'Gerência Financeira',
    assunto: 'Pagamento de diárias - Visita técnica IFMA',
    situacao: 'Concluído',
    projetoDescricao: 'Cooperação Técnica IFMA',
    numeroConvenio: 'CONV-2025-020',
    documentCount: 6,
    lastUpdated: subDays(new Date(), 7).toISOString(),
  },
  {
    id: 'prot_11',
    numeroProtocolo: 1513,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 8).toISOString(),
    codigoOrigem: 9,
    setorOrigem: 'Contabilidade',
    codigoDestino: 4,
    setorDestino: 'Gerência Financeira',
    assunto: 'Conciliação bancária - Janeiro 2026',
    situacao: 'Concluído',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 12,
    lastUpdated: subDays(new Date(), 8).toISOString(),
  },
  {
    id: 'prot_12',
    numeroProtocolo: 1512,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 10).toISOString(),
    codigoOrigem: 10,
    setorOrigem: 'Jurídico',
    codigoDestino: 1,
    setorDestino: 'Superintendência',
    assunto: 'Parecer jurídico - Credenciamento UESPI',
    situacao: 'Concluído',
    projetoDescricao: 'Credenciamento UESPI',
    numeroConvenio: null,
    documentCount: 3,
    lastUpdated: subDays(new Date(), 10).toISOString(),
  },
  {
    id: 'prot_13',
    numeroProtocolo: 1511,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 12).toISOString(),
    codigoOrigem: 3,
    setorOrigem: 'Gerência de Projetos',
    codigoDestino: 5,
    setorDestino: 'Gerência de TI',
    assunto: 'Solicitação de acesso ao SAGI - Novo analista',
    situacao: 'Concluído',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 1,
    lastUpdated: subDays(new Date(), 12).toISOString(),
  },
  {
    id: 'prot_14',
    numeroProtocolo: 1510,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 14).toISOString(),
    codigoOrigem: 7,
    setorOrigem: 'Recursos Humanos',
    codigoDestino: 4,
    setorDestino: 'Gerência Financeira',
    assunto: 'Folha de pagamento - Bolsistas fevereiro 2026',
    situacao: 'Em Andamento',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 0,
    lastUpdated: subDays(new Date(), 14).toISOString(),
  },
  {
    id: 'prot_15',
    numeroProtocolo: 1509,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 15).toISOString(),
    codigoOrigem: 12,
    setorOrigem: 'Almoxarifado',
    codigoDestino: 8,
    setorDestino: 'Compras e Licitações',
    assunto: 'Requisição de material de consumo',
    situacao: 'Pendente',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 0,
    lastUpdated: subDays(new Date(), 15).toISOString(),
  },
  {
    id: 'prot_16',
    numeroProtocolo: 1508,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 18).toISOString(),
    codigoOrigem: 5,
    setorOrigem: 'Gerência de TI',
    codigoDestino: 2,
    setorDestino: 'Diretoria Executiva',
    assunto: 'Proposta de implantação do GED FADEX',
    situacao: 'Concluído',
    projetoDescricao: 'GED FADEX',
    numeroConvenio: null,
    documentCount: 8,
    lastUpdated: subDays(new Date(), 18).toISOString(),
  },
  {
    id: 'prot_17',
    numeroProtocolo: 1507,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 20).toISOString(),
    codigoOrigem: 3,
    setorOrigem: 'Gerência de Projetos',
    codigoDestino: 9,
    setorDestino: 'Contabilidade',
    assunto: 'Relatório financeiro trimestral - UFPB',
    situacao: 'Cancelado',
    projetoDescricao: 'Cooperação UFPB 2025',
    numeroConvenio: 'CONV-2025-005',
    documentCount: 2,
    lastUpdated: subDays(new Date(), 20).toISOString(),
  },
  {
    id: 'prot_18',
    numeroProtocolo: 1506,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 22).toISOString(),
    codigoOrigem: 4,
    setorOrigem: 'Gerência Financeira',
    codigoDestino: 3,
    setorDestino: 'Gerência de Projetos',
    assunto: 'Devolução de saldo - Rubrica 33.90.30',
    situacao: 'Concluído',
    projetoDescricao: 'Capacitação Docente UFDPar',
    numeroConvenio: 'CONV-2025-015',
    documentCount: 4,
    lastUpdated: subDays(new Date(), 22).toISOString(),
  },
  {
    id: 'prot_19',
    numeroProtocolo: 1505,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 25).toISOString(),
    codigoOrigem: 6,
    setorOrigem: 'Gerência Administrativa',
    codigoDestino: 7,
    setorDestino: 'Recursos Humanos',
    assunto: 'Comunicado interno - Horário de expediente Carnaval',
    situacao: 'Concluído',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 1,
    lastUpdated: subDays(new Date(), 25).toISOString(),
  },
  {
    id: 'prot_20',
    numeroProtocolo: 1504,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 28).toISOString(),
    codigoOrigem: 3,
    setorOrigem: 'Gerência de Projetos',
    codigoDestino: 10,
    setorDestino: 'Jurídico',
    assunto: 'Minuta de convênio - IFSertão',
    situacao: 'Pendente',
    projetoDescricao: 'Pesquisa IFSertão 2026',
    numeroConvenio: null,
    documentCount: 3,
    lastUpdated: subDays(new Date(), 28).toISOString(),
  },
  {
    id: 'prot_21',
    numeroProtocolo: 1503,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 30).toISOString(),
    codigoOrigem: 8,
    setorOrigem: 'Compras e Licitações',
    codigoDestino: 3,
    setorDestino: 'Gerência de Projetos',
    assunto: 'Homologação de pregão eletrônico nº 03/2026',
    situacao: 'Concluído',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 15,
    lastUpdated: subDays(new Date(), 30).toISOString(),
  },
  {
    id: 'prot_22',
    numeroProtocolo: 1502,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 35).toISOString(),
    codigoOrigem: 5,
    setorOrigem: 'Gerência de TI',
    codigoDestino: 5,
    setorDestino: 'Gerência de TI',
    assunto: 'Backup e migração de dados - Servidor SAGI',
    situacao: 'Em Andamento',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 0,
    lastUpdated: subDays(new Date(), 35).toISOString(),
  },
  {
    id: 'prot_23',
    numeroProtocolo: 1501,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 40).toISOString(),
    codigoOrigem: 11,
    setorOrigem: 'Patrimônio',
    codigoDestino: 6,
    setorDestino: 'Gerência Administrativa',
    assunto: 'Relatório de baixa patrimonial - Equipamentos obsoletos',
    situacao: 'Concluído',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 9,
    lastUpdated: subDays(new Date(), 40).toISOString(),
  },
  {
    id: 'prot_24',
    numeroProtocolo: 1500,
    anoProtocolo: 2026,
    dataProtocolo: subDays(new Date(), 45).toISOString(),
    codigoOrigem: 2,
    setorOrigem: 'Diretoria Executiva',
    codigoDestino: 1,
    setorDestino: 'Superintendência',
    assunto: 'Planejamento estratégico 2026 - Apresentação',
    situacao: 'Concluído',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 6,
    lastUpdated: subDays(new Date(), 45).toISOString(),
  },
  {
    id: 'prot_25',
    numeroProtocolo: 1499,
    anoProtocolo: 2025,
    dataProtocolo: subDays(new Date(), 50).toISOString(),
    codigoOrigem: 3,
    setorOrigem: 'Gerência de Projetos',
    codigoDestino: 4,
    setorDestino: 'Gerência Financeira',
    assunto: 'Encerramento financeiro - Convênio UNIVASF 2025',
    situacao: 'Cancelado',
    projetoDescricao: 'Cooperação UNIVASF 2025',
    numeroConvenio: 'CONV-2025-018',
    documentCount: 0,
    lastUpdated: subDays(new Date(), 50).toISOString(),
  },
  {
    id: 'prot_26',
    numeroProtocolo: 1498,
    anoProtocolo: 2025,
    dataProtocolo: subDays(new Date(), 55).toISOString(),
    codigoOrigem: 4,
    setorOrigem: 'Gerência Financeira',
    codigoDestino: 2,
    setorDestino: 'Diretoria Executiva',
    assunto: 'Relatório de aplicações financeiras - Dezembro 2025',
    situacao: 'Concluído',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 3,
    lastUpdated: subDays(new Date(), 55).toISOString(),
  },
  {
    id: 'prot_27',
    numeroProtocolo: 1497,
    anoProtocolo: 2025,
    dataProtocolo: subDays(new Date(), 60).toISOString(),
    codigoOrigem: 5,
    setorOrigem: 'Gerência de TI',
    codigoDestino: 3,
    setorDestino: 'Gerência de Projetos',
    assunto: 'Especificação técnica - Sistema GED',
    situacao: 'Concluído',
    projetoDescricao: 'GED FADEX',
    numeroConvenio: null,
    documentCount: 10,
    lastUpdated: subDays(new Date(), 60).toISOString(),
  },
  {
    id: 'prot_28',
    numeroProtocolo: 1496,
    anoProtocolo: 2025,
    dataProtocolo: subDays(new Date(), 75).toISOString(),
    codigoOrigem: 7,
    setorOrigem: 'Recursos Humanos',
    codigoDestino: 10,
    setorDestino: 'Jurídico',
    assunto: 'Consulta trabalhista - Regime de bolsistas',
    situacao: 'Concluído',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 2,
    lastUpdated: subDays(new Date(), 75).toISOString(),
  },
  {
    id: 'prot_29',
    numeroProtocolo: 1495,
    anoProtocolo: 2025,
    dataProtocolo: subDays(new Date(), 85).toISOString(),
    codigoOrigem: 3,
    setorOrigem: 'Gerência de Projetos',
    codigoDestino: 8,
    setorDestino: 'Compras e Licitações',
    assunto: 'Abertura de processo licitatório - Mobiliário',
    situacao: 'Concluído',
    projetoDescricao: 'Nova Sede Administrativa',
    numeroConvenio: 'CONV-2025-002',
    documentCount: 20,
    lastUpdated: subDays(new Date(), 85).toISOString(),
  },
  {
    id: 'prot_30',
    numeroProtocolo: 1494,
    anoProtocolo: 2025,
    dataProtocolo: subDays(new Date(), 90).toISOString(),
    codigoOrigem: 9,
    setorOrigem: 'Contabilidade',
    codigoDestino: 1,
    setorDestino: 'Superintendência',
    assunto: 'Balancete consolidado - Novembro 2025',
    situacao: 'Concluído',
    projetoDescricao: null,
    numeroConvenio: null,
    documentCount: 5,
    lastUpdated: subDays(new Date(), 90).toISOString(),
  },
];
