// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_logs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityLog = `-- name: CreateActivityLog :exec
INSERT INTO activity_logs (
    acao, entidade, entidade_id, detalhes,
    usuario_email, usuario_nome, ip_address
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateActivityLogParams struct {
	Acao         string          `json:"acao"`
	Entidade     string          `json:"entidade"`
	EntidadeID   pgtype.Text     `json:"entidade_id"`
	Detalhes     json.RawMessage `json:"detalhes"`
	UsuarioEmail string          `json:"usuario_email"`
	UsuarioNome  string          `json:"usuario_nome"`
	IpAddress    pgtype.Text     `json:"ip_address"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error {
	_, err := q.db.Exec(ctx, createActivityLog,
		arg.Acao,
		arg.Entidade,
		arg.EntidadeID,
		arg.Detalhes,
		arg.UsuarioEmail,
		arg.UsuarioNome,
		arg.IpAddress,
	)
	return err
}

const listActivityLogs = `-- name: ListActivityLogs :many
SELECT id, acao, entidade, entidade_id, detalhes, usuario_email, usuario_nome, ip_address, criado_em FROM activity_logs
WHERE
    ($3::varchar IS NULL OR entidade = $3)
    AND ($4::varchar IS NULL OR usuario_email = $4)
    AND ($5::timestamp IS NULL OR criado_em >= $5)
    AND ($6::timestamp IS NULL OR criado_em <= $6)
ORDER BY criado_em DESC
LIMIT $1 OFFSET $2
`

type ListActivityLogsParams struct {
	Limit        int32            `json:"limit"`
	Offset       int32            `json:"offset"`
	Entidade     pgtype.Text      `json:"entidade"`
	UsuarioEmail pgtype.Text      `json:"usuario_email"`
	Desde        pgtype.Timestamp `json:"desde"`
	Ate          pgtype.Timestamp `json:"ate"`
}

func (q *Queries) ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogs,
		arg.Limit,
		arg.Offset,
		arg.Entidade,
		arg.UsuarioEmail,
		arg.Desde,
		arg.Ate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.Acao,
			&i.Entidade,
			&i.EntidadeID,
			&i.Detalhes,
			&i.UsuarioEmail,
			&i.UsuarioNome,
			&i.IpAddress,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
