// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admins.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateAdmin = `-- name: ActivateAdmin :exec
UPDATE admins SET ativo = true, atualizado_em = NOW()
WHERE id = $1
`

func (q *Queries) ActivateAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, activateAdmin, id)
	return err
}

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM admins
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (email, nome, role, criado_por)
VALUES ($1, $2, $3, $4)
RETURNING id, email, nome, role, ativo, criado_por, criado_em, atualizado_em, setor
`

type CreateAdminParams struct {
	Email     string      `json:"email"`
	Nome      string      `json:"nome"`
	Role      string      `json:"role"`
	CriadoPor pgtype.Text `json:"criado_por"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.Email,
		arg.Nome,
		arg.Role,
		arg.CriadoPor,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nome,
		&i.Role,
		&i.Ativo,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.Setor,
	)
	return i, err
}

const deactivateAdmin = `-- name: DeactivateAdmin :exec
UPDATE admins SET ativo = false, atualizado_em = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateAdmin, id)
	return err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, nome, role, ativo, criado_por, criado_em, atualizado_em, setor FROM admins
WHERE email = $1 AND ativo = true
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nome,
		&i.Role,
		&i.Ativo,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.Setor,
	)
	return i, err
}

const getAdminByEmailAny = `-- name: GetAdminByEmailAny :one
SELECT id, email, nome, role, ativo, criado_por, criado_em, atualizado_em, setor FROM admins
WHERE email = $1
`

func (q *Queries) GetAdminByEmailAny(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmailAny, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nome,
		&i.Role,
		&i.Ativo,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.Setor,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, nome, role, ativo, criado_por, criado_em, atualizado_em, setor FROM admins
WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nome,
		&i.Role,
		&i.Ativo,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.Setor,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, email, nome, role, ativo, criado_por, criado_em, atualizado_em, setor FROM admins
ORDER BY criado_em DESC
LIMIT $1 OFFSET $2
`

type ListAdminsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAdmins(ctx context.Context, arg ListAdminsParams) ([]Admin, error) {
	rows, err := q.db.Query(ctx, listAdmins, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Admin{}
	for rows.Next() {
		var i Admin
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Nome,
			&i.Role,
			&i.Ativo,
			&i.CriadoPor,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.Setor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminRole = `-- name: UpdateAdminRole :exec
UPDATE admins SET role = $2, atualizado_em = NOW()
WHERE id = $1
`

type UpdateAdminRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateAdminRole(ctx context.Context, arg UpdateAdminRoleParams) error {
	_, err := q.db.Exec(ctx, updateAdminRole, arg.ID, arg.Role)
	return err
}
