// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cache_email_setor.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSetorByEmail = `-- name: GetSetorByEmail :one
SELECT email, setor, nome, atualizado_em FROM cache_email_setor
WHERE email = $1
`

func (q *Queries) GetSetorByEmail(ctx context.Context, email string) (CacheEmailSetor, error) {
	row := q.db.QueryRow(ctx, getSetorByEmail, email)
	var i CacheEmailSetor
	err := row.Scan(
		&i.Email,
		&i.Setor,
		&i.Nome,
		&i.AtualizadoEm,
	)
	return i, err
}

const listCacheEmailSetor = `-- name: ListCacheEmailSetor :many
SELECT email, setor, nome, atualizado_em FROM cache_email_setor
ORDER BY nome
`

func (q *Queries) ListCacheEmailSetor(ctx context.Context) ([]CacheEmailSetor, error) {
	rows, err := q.db.Query(ctx, listCacheEmailSetor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CacheEmailSetor{}
	for rows.Next() {
		var i CacheEmailSetor
		if err := rows.Scan(
			&i.Email,
			&i.Setor,
			&i.Nome,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCacheEmailSetor = `-- name: UpsertCacheEmailSetor :exec
INSERT INTO cache_email_setor (email, setor, nome)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO UPDATE
SET setor = EXCLUDED.setor, nome = EXCLUDED.nome, atualizado_em = NOW()
`

type UpsertCacheEmailSetorParams struct {
	Email string      `json:"email"`
	Setor string      `json:"setor"`
	Nome  pgtype.Text `json:"nome"`
}

func (q *Queries) UpsertCacheEmailSetor(ctx context.Context, arg UpsertCacheEmailSetorParams) error {
	_, err := q.db.Exec(ctx, upsertCacheEmailSetor, arg.Email, arg.Setor, arg.Nome)
	return err
}
