// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardCountDocumentos = `-- name: DashboardCountDocumentos :one
SELECT COUNT(*) FROM documentos
WHERE deleted_at IS NULL
  AND ($1::timestamp IS NULL OR uploaded_at >= $1)
  AND ($2::text = '' OR uploaded_by_name ILIKE '%' || $2 || '%')
`

type DashboardCountDocumentosParams struct {
	Column1 pgtype.Timestamp `json:"column_1"`
	Column2 string           `json:"column_2"`
}

func (q *Queries) DashboardCountDocumentos(ctx context.Context, arg DashboardCountDocumentosParams) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardCountDocumentos, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardCountObservacoes = `-- name: DashboardCountObservacoes :one
SELECT COUNT(*) FROM observacoes
WHERE deleted_at IS NULL
  AND ($1::timestamp IS NULL OR criado_em >= $1)
`

func (q *Queries) DashboardCountObservacoes(ctx context.Context, dollar_1 pgtype.Timestamp) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardCountObservacoes, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardDocsPorTipo = `-- name: DashboardDocsPorTipo :many
SELECT
    COALESCE(td.nome, 'Sem tipo') AS tipo,
    COUNT(*) AS quantidade
FROM documentos d
LEFT JOIN tipos_documento td ON td.id = d.tipo_documento_id
WHERE d.deleted_at IS NULL
  AND ($1::timestamp IS NULL OR d.uploaded_at >= $1)
GROUP BY COALESCE(td.nome, 'Sem tipo')
ORDER BY quantidade DESC
`

type DashboardDocsPorTipoRow struct {
	Tipo       string `json:"tipo"`
	Quantidade int64  `json:"quantidade"`
}

func (q *Queries) DashboardDocsPorTipo(ctx context.Context, dollar_1 pgtype.Timestamp) ([]DashboardDocsPorTipoRow, error) {
	rows, err := q.db.Query(ctx, dashboardDocsPorTipo, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardDocsPorTipoRow{}
	for rows.Next() {
		var i DashboardDocsPorTipoRow
		if err := rows.Scan(&i.Tipo, &i.Quantidade); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardProtocolosComDocs = `-- name: DashboardProtocolosComDocs :many
SELECT DISTINCT protocolo_sagi FROM documentos
WHERE deleted_at IS NULL
`

func (q *Queries) DashboardProtocolosComDocs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, dashboardProtocolosComDocs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var protocolo_sagi string
		if err := rows.Scan(&protocolo_sagi); err != nil {
			return nil, err
		}
		items = append(items, protocolo_sagi)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardProtocolosInternosPorDia = `-- name: DashboardProtocolosInternosPorDia :many
SELECT
    TO_CHAR(created_at, 'YYYY-MM-DD') AS data,
    COUNT(*) AS total
FROM internal_protocols
WHERE is_deleted = FALSE
  AND created_at >= $1
GROUP BY TO_CHAR(created_at, 'YYYY-MM-DD')
ORDER BY data
`

type DashboardProtocolosInternosPorDiaRow struct {
	Data  string `json:"data"`
	Total int64  `json:"total"`
}

func (q *Queries) DashboardProtocolosInternosPorDia(ctx context.Context, createdAt pgtype.Timestamptz) ([]DashboardProtocolosInternosPorDiaRow, error) {
	rows, err := q.db.Query(ctx, dashboardProtocolosInternosPorDia, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardProtocolosInternosPorDiaRow{}
	for rows.Next() {
		var i DashboardProtocolosInternosPorDiaRow
		if err := rows.Scan(&i.Data, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRankingUploads = `-- name: DashboardRankingUploads :many
SELECT
    COALESCE(d.uploaded_by_name, d.uploaded_by) AS nome,
    d.uploaded_by AS email,
    COUNT(*) AS uploads
FROM documentos d
WHERE d.deleted_at IS NULL
  AND ($1::timestamp IS NULL OR d.uploaded_at >= $1)
GROUP BY COALESCE(d.uploaded_by_name, d.uploaded_by), d.uploaded_by
ORDER BY uploads DESC
LIMIT $2
`

type DashboardRankingUploadsParams struct {
	Column1 pgtype.Timestamp `json:"column_1"`
	Limit   int32            `json:"limit"`
}

type DashboardRankingUploadsRow struct {
	Nome    string `json:"nome"`
	Email   string `json:"email"`
	Uploads int64  `json:"uploads"`
}

func (q *Queries) DashboardRankingUploads(ctx context.Context, arg DashboardRankingUploadsParams) ([]DashboardRankingUploadsRow, error) {
	rows, err := q.db.Query(ctx, dashboardRankingUploads, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRankingUploadsRow{}
	for rows.Next() {
		var i DashboardRankingUploadsRow
		if err := rows.Scan(&i.Nome, &i.Email, &i.Uploads); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardUploadsPorDia = `-- name: DashboardUploadsPorDia :many
SELECT
    TO_CHAR(uploaded_at, 'YYYY-MM-DD') AS data,
    COUNT(*) AS total
FROM documentos
WHERE deleted_at IS NULL
  AND uploaded_at >= $1
GROUP BY TO_CHAR(uploaded_at, 'YYYY-MM-DD')
ORDER BY data
`

type DashboardUploadsPorDiaRow struct {
	Data  string `json:"data"`
	Total int64  `json:"total"`
}

func (q *Queries) DashboardUploadsPorDia(ctx context.Context, uploadedAt pgtype.Timestamp) ([]DashboardUploadsPorDiaRow, error) {
	rows, err := q.db.Query(ctx, dashboardUploadsPorDia, uploadedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardUploadsPorDiaRow{}
	for rows.Next() {
		var i DashboardUploadsPorDiaRow
		if err := rows.Scan(&i.Data, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
