// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: internal_protocols.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDocsByInternalProtocolIDs = `-- name: CountDocsByInternalProtocolIDs :many
SELECT protocolo_sagi, COUNT(*) AS doc_count
FROM documentos
WHERE protocolo_sagi = ANY($1::varchar[])
  AND deleted_at IS NULL
GROUP BY protocolo_sagi
`

type CountDocsByInternalProtocolIDsRow struct {
	ProtocoloSagi string `json:"protocolo_sagi"`
	DocCount      int64  `json:"doc_count"`
}

func (q *Queries) CountDocsByInternalProtocolIDs(ctx context.Context, dollar_1 []string) ([]CountDocsByInternalProtocolIDsRow, error) {
	rows, err := q.db.Query(ctx, countDocsByInternalProtocolIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDocsByInternalProtocolIDsRow{}
	for rows.Next() {
		var i CountDocsByInternalProtocolIDsRow
		if err := rows.Scan(&i.ProtocoloSagi, &i.DocCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countInternalProtocols = `-- name: CountInternalProtocols :one
SELECT COUNT(*) FROM internal_protocols
WHERE is_deleted = FALSE
  AND ($1::INTEGER IS NULL OR current_sector_code = $1)
  AND ($2::VARCHAR IS NULL OR status = $2)
  AND ($3::VARCHAR IS NULL OR (
    subject ILIKE '%' || $3 || '%'
    OR protocol_number ILIKE '%' || $3 || '%'
    OR interested ILIKE '%' || $3 || '%'
    OR project_name ILIKE '%' || $3 || '%'
    OR current_sector_name ILIKE '%' || $3 || '%'
    OR observations ILIKE '%' || $3 || '%'
  ))
  AND ($4::VARCHAR IS NULL OR project_name ILIKE '%' || $4 || '%')
`

type CountInternalProtocolsParams struct {
	SectorCode  pgtype.Int4 `json:"sector_code"`
	Status      pgtype.Text `json:"status"`
	Search      pgtype.Text `json:"search"`
	ProjectName pgtype.Text `json:"project_name"`
}

func (q *Queries) CountInternalProtocols(ctx context.Context, arg CountInternalProtocolsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInternalProtocols,
		arg.SectorCode,
		arg.Status,
		arg.Search,
		arg.ProjectName,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMovementsByProtocolID = `-- name: CountMovementsByProtocolID :one
SELECT COUNT(*) FROM internal_protocol_movements
WHERE protocol_id = $1
`

func (q *Queries) CountMovementsByProtocolID(ctx context.Context, protocolID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countMovementsByProtocolID, protocolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countObsByInternalProtocolIDs = `-- name: CountObsByInternalProtocolIDs :many
SELECT protocolo_sagi, COUNT(*) AS obs_count
FROM observacoes
WHERE protocolo_sagi = ANY($1::varchar[])
  AND deleted_at IS NULL
GROUP BY protocolo_sagi
`

type CountObsByInternalProtocolIDsRow struct {
	ProtocoloSagi string `json:"protocolo_sagi"`
	ObsCount      int64  `json:"obs_count"`
}

func (q *Queries) CountObsByInternalProtocolIDs(ctx context.Context, dollar_1 []string) ([]CountObsByInternalProtocolIDsRow, error) {
	rows, err := q.db.Query(ctx, countObsByInternalProtocolIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountObsByInternalProtocolIDsRow{}
	for rows.Next() {
		var i CountObsByInternalProtocolIDsRow
		if err := rows.Scan(&i.ProtocoloSagi, &i.ObsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createInternalProtocol = `-- name: CreateInternalProtocol :one
INSERT INTO internal_protocols (
    protocol_number, year, sequence,
    subject, interested, sender, project_name,
    current_sector_code, current_sector_name,
    created_by_id, created_by_email, created_by_name,
    observations
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, protocol_number, year, sequence, subject, interested, sender, project_name, current_sector_code, current_sector_name, status, cancel_reason, created_by_id, created_by_email, created_by_name, created_at, updated_at, is_deleted, deleted_at, deleted_by_email, delete_reason, observations
`

type CreateInternalProtocolParams struct {
	ProtocolNumber    string      `json:"protocol_number"`
	Year              int32       `json:"year"`
	Sequence          int32       `json:"sequence"`
	Subject           string      `json:"subject"`
	Interested        string      `json:"interested"`
	Sender            string      `json:"sender"`
	ProjectName       string      `json:"project_name"`
	CurrentSectorCode int32       `json:"current_sector_code"`
	CurrentSectorName string      `json:"current_sector_name"`
	CreatedByID       string      `json:"created_by_id"`
	CreatedByEmail    string      `json:"created_by_email"`
	CreatedByName     pgtype.Text `json:"created_by_name"`
	Observations      string      `json:"observations"`
}

func (q *Queries) CreateInternalProtocol(ctx context.Context, arg CreateInternalProtocolParams) (InternalProtocol, error) {
	row := q.db.QueryRow(ctx, createInternalProtocol,
		arg.ProtocolNumber,
		arg.Year,
		arg.Sequence,
		arg.Subject,
		arg.Interested,
		arg.Sender,
		arg.ProjectName,
		arg.CurrentSectorCode,
		arg.CurrentSectorName,
		arg.CreatedByID,
		arg.CreatedByEmail,
		arg.CreatedByName,
		arg.Observations,
	)
	var i InternalProtocol
	err := row.Scan(
		&i.ID,
		&i.ProtocolNumber,
		&i.Year,
		&i.Sequence,
		&i.Subject,
		&i.Interested,
		&i.Sender,
		&i.ProjectName,
		&i.CurrentSectorCode,
		&i.CurrentSectorName,
		&i.Status,
		&i.CancelReason,
		&i.CreatedByID,
		&i.CreatedByEmail,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedByEmail,
		&i.DeleteReason,
		&i.Observations,
	)
	return i, err
}

const getInternalProtocolByID = `-- name: GetInternalProtocolByID :one
SELECT id, protocol_number, year, sequence, subject, interested, sender, project_name, current_sector_code, current_sector_name, status, cancel_reason, created_by_id, created_by_email, created_by_name, created_at, updated_at, is_deleted, deleted_at, deleted_by_email, delete_reason, observations FROM internal_protocols WHERE id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetInternalProtocolByID(ctx context.Context, id int32) (InternalProtocol, error) {
	row := q.db.QueryRow(ctx, getInternalProtocolByID, id)
	var i InternalProtocol
	err := row.Scan(
		&i.ID,
		&i.ProtocolNumber,
		&i.Year,
		&i.Sequence,
		&i.Subject,
		&i.Interested,
		&i.Sender,
		&i.ProjectName,
		&i.CurrentSectorCode,
		&i.CurrentSectorName,
		&i.Status,
		&i.CancelReason,
		&i.CreatedByID,
		&i.CreatedByEmail,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedByEmail,
		&i.DeleteReason,
		&i.Observations,
	)
	return i, err
}

const getNextSequence = `-- name: GetNextSequence :one
SELECT COALESCE(MAX(sequence), 0) + 1 AS next_seq
FROM internal_protocols WHERE year = $1
`

func (q *Queries) GetNextSequence(ctx context.Context, year int32) (int32, error) {
	row := q.db.QueryRow(ctx, getNextSequence, year)
	var next_seq int32
	err := row.Scan(&next_seq)
	return next_seq, err
}

const listInternalProtocols = `-- name: ListInternalProtocols :many
SELECT id, protocol_number, year, sequence, subject, interested, sender, project_name, current_sector_code, current_sector_name, status, cancel_reason, created_by_id, created_by_email, created_by_name, created_at, updated_at, is_deleted, deleted_at, deleted_by_email, delete_reason, observations FROM internal_protocols
WHERE is_deleted = FALSE
  AND ($3::INTEGER IS NULL OR current_sector_code = $3)
  AND ($4::VARCHAR IS NULL OR status = $4)
  AND ($5::VARCHAR IS NULL OR (
    subject ILIKE '%' || $5 || '%'
    OR protocol_number ILIKE '%' || $5 || '%'
    OR interested ILIKE '%' || $5 || '%'
    OR project_name ILIKE '%' || $5 || '%'
    OR current_sector_name ILIKE '%' || $5 || '%'
    OR observations ILIKE '%' || $5 || '%'
  ))
  AND ($6::VARCHAR IS NULL OR project_name ILIKE '%' || $6 || '%')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListInternalProtocolsParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	SectorCode  pgtype.Int4 `json:"sector_code"`
	Status      pgtype.Text `json:"status"`
	Search      pgtype.Text `json:"search"`
	ProjectName pgtype.Text `json:"project_name"`
}

func (q *Queries) ListInternalProtocols(ctx context.Context, arg ListInternalProtocolsParams) ([]InternalProtocol, error) {
	rows, err := q.db.Query(ctx, listInternalProtocols,
		arg.Limit,
		arg.Offset,
		arg.SectorCode,
		arg.Status,
		arg.Search,
		arg.ProjectName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InternalProtocol{}
	for rows.Next() {
		var i InternalProtocol
		if err := rows.Scan(
			&i.ID,
			&i.ProtocolNumber,
			&i.Year,
			&i.Sequence,
			&i.Subject,
			&i.Interested,
			&i.Sender,
			&i.ProjectName,
			&i.CurrentSectorCode,
			&i.CurrentSectorName,
			&i.Status,
			&i.CancelReason,
			&i.CreatedByID,
			&i.CreatedByEmail,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.DeletedByEmail,
			&i.DeleteReason,
			&i.Observations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteInternalProtocol = `-- name: SoftDeleteInternalProtocol :one
UPDATE internal_protocols
SET is_deleted = TRUE, deleted_at = NOW(),
    deleted_by_email = $2, delete_reason = $3
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, protocol_number, year, sequence, subject, interested, sender, project_name, current_sector_code, current_sector_name, status, cancel_reason, created_by_id, created_by_email, created_by_name, created_at, updated_at, is_deleted, deleted_at, deleted_by_email, delete_reason, observations
`

type SoftDeleteInternalProtocolParams struct {
	ID             int32       `json:"id"`
	DeletedByEmail pgtype.Text `json:"deleted_by_email"`
	DeleteReason   pgtype.Text `json:"delete_reason"`
}

func (q *Queries) SoftDeleteInternalProtocol(ctx context.Context, arg SoftDeleteInternalProtocolParams) (InternalProtocol, error) {
	row := q.db.QueryRow(ctx, softDeleteInternalProtocol, arg.ID, arg.DeletedByEmail, arg.DeleteReason)
	var i InternalProtocol
	err := row.Scan(
		&i.ID,
		&i.ProtocolNumber,
		&i.Year,
		&i.Sequence,
		&i.Subject,
		&i.Interested,
		&i.Sender,
		&i.ProjectName,
		&i.CurrentSectorCode,
		&i.CurrentSectorName,
		&i.Status,
		&i.CancelReason,
		&i.CreatedByID,
		&i.CreatedByEmail,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedByEmail,
		&i.DeleteReason,
		&i.Observations,
	)
	return i, err
}

const updateInternalProtocol = `-- name: UpdateInternalProtocol :one
UPDATE internal_protocols
SET subject = COALESCE($2, subject),
    interested = COALESCE($3, interested),
    sender = COALESCE($4, sender),
    project_name = COALESCE($5, project_name),
    observations = COALESCE($6, observations)
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, protocol_number, year, sequence, subject, interested, sender, project_name, current_sector_code, current_sector_name, status, cancel_reason, created_by_id, created_by_email, created_by_name, created_at, updated_at, is_deleted, deleted_at, deleted_by_email, delete_reason, observations
`

type UpdateInternalProtocolParams struct {
	ID           int32       `json:"id"`
	Subject      pgtype.Text `json:"subject"`
	Interested   pgtype.Text `json:"interested"`
	Sender       pgtype.Text `json:"sender"`
	ProjectName  pgtype.Text `json:"project_name"`
	Observations pgtype.Text `json:"observations"`
}

func (q *Queries) UpdateInternalProtocol(ctx context.Context, arg UpdateInternalProtocolParams) (InternalProtocol, error) {
	row := q.db.QueryRow(ctx, updateInternalProtocol,
		arg.ID,
		arg.Subject,
		arg.Interested,
		arg.Sender,
		arg.ProjectName,
		arg.Observations,
	)
	var i InternalProtocol
	err := row.Scan(
		&i.ID,
		&i.ProtocolNumber,
		&i.Year,
		&i.Sequence,
		&i.Subject,
		&i.Interested,
		&i.Sender,
		&i.ProjectName,
		&i.CurrentSectorCode,
		&i.CurrentSectorName,
		&i.Status,
		&i.CancelReason,
		&i.CreatedByID,
		&i.CreatedByEmail,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedByEmail,
		&i.DeleteReason,
		&i.Observations,
	)
	return i, err
}

const updateInternalProtocolSector = `-- name: UpdateInternalProtocolSector :exec
UPDATE internal_protocols
SET current_sector_code = $2, current_sector_name = $3
WHERE id = $1
`

type UpdateInternalProtocolSectorParams struct {
	ID                int32  `json:"id"`
	CurrentSectorCode int32  `json:"current_sector_code"`
	CurrentSectorName string `json:"current_sector_name"`
}

func (q *Queries) UpdateInternalProtocolSector(ctx context.Context, arg UpdateInternalProtocolSectorParams) error {
	_, err := q.db.Exec(ctx, updateInternalProtocolSector, arg.ID, arg.CurrentSectorCode, arg.CurrentSectorName)
	return err
}

const updateInternalProtocolStatus = `-- name: UpdateInternalProtocolStatus :one
UPDATE internal_protocols
SET status = $2, cancel_reason = $3
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, protocol_number, year, sequence, subject, interested, sender, project_name, current_sector_code, current_sector_name, status, cancel_reason, created_by_id, created_by_email, created_by_name, created_at, updated_at, is_deleted, deleted_at, deleted_by_email, delete_reason, observations
`

type UpdateInternalProtocolStatusParams struct {
	ID           int32       `json:"id"`
	Status       string      `json:"status"`
	CancelReason pgtype.Text `json:"cancel_reason"`
}

func (q *Queries) UpdateInternalProtocolStatus(ctx context.Context, arg UpdateInternalProtocolStatusParams) (InternalProtocol, error) {
	row := q.db.QueryRow(ctx, updateInternalProtocolStatus, arg.ID, arg.Status, arg.CancelReason)
	var i InternalProtocol
	err := row.Scan(
		&i.ID,
		&i.ProtocolNumber,
		&i.Year,
		&i.Sequence,
		&i.Subject,
		&i.Interested,
		&i.Sender,
		&i.ProjectName,
		&i.CurrentSectorCode,
		&i.CurrentSectorName,
		&i.Status,
		&i.CancelReason,
		&i.CreatedByID,
		&i.CreatedByEmail,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedByEmail,
		&i.DeleteReason,
		&i.Observations,
	)
	return i, err
}
