// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: internal_movements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearCurrentFlag = `-- name: ClearCurrentFlag :exec
UPDATE internal_protocol_movements
SET is_current = FALSE
WHERE protocol_id = $1 AND is_current = TRUE
`

func (q *Queries) ClearCurrentFlag(ctx context.Context, protocolID int32) error {
	_, err := q.db.Exec(ctx, clearCurrentFlag, protocolID)
	return err
}

const createMovement = `-- name: CreateMovement :one
INSERT INTO internal_protocol_movements (
    protocol_id, sequence,
    from_sector_code, from_sector_name,
    to_sector_code, to_sector_name,
    dispatch_note,
    moved_by_id, moved_by_email, moved_by_name
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, protocol_id, sequence, from_sector_code, from_sector_name, to_sector_code, to_sector_name, dispatch_note, moved_by_id, moved_by_email, moved_by_name, moved_at, is_current
`

type CreateMovementParams struct {
	ProtocolID     int32       `json:"protocol_id"`
	Sequence       int32       `json:"sequence"`
	FromSectorCode pgtype.Int4 `json:"from_sector_code"`
	FromSectorName pgtype.Text `json:"from_sector_name"`
	ToSectorCode   int32       `json:"to_sector_code"`
	ToSectorName   string      `json:"to_sector_name"`
	DispatchNote   string      `json:"dispatch_note"`
	MovedByID      string      `json:"moved_by_id"`
	MovedByEmail   string      `json:"moved_by_email"`
	MovedByName    pgtype.Text `json:"moved_by_name"`
}

func (q *Queries) CreateMovement(ctx context.Context, arg CreateMovementParams) (InternalProtocolMovement, error) {
	row := q.db.QueryRow(ctx, createMovement,
		arg.ProtocolID,
		arg.Sequence,
		arg.FromSectorCode,
		arg.FromSectorName,
		arg.ToSectorCode,
		arg.ToSectorName,
		arg.DispatchNote,
		arg.MovedByID,
		arg.MovedByEmail,
		arg.MovedByName,
	)
	var i InternalProtocolMovement
	err := row.Scan(
		&i.ID,
		&i.ProtocolID,
		&i.Sequence,
		&i.FromSectorCode,
		&i.FromSectorName,
		&i.ToSectorCode,
		&i.ToSectorName,
		&i.DispatchNote,
		&i.MovedByID,
		&i.MovedByEmail,
		&i.MovedByName,
		&i.MovedAt,
		&i.IsCurrent,
	)
	return i, err
}

const getCurrentMovement = `-- name: GetCurrentMovement :one
SELECT id, protocol_id, sequence, from_sector_code, from_sector_name, to_sector_code, to_sector_name, dispatch_note, moved_by_id, moved_by_email, moved_by_name, moved_at, is_current FROM internal_protocol_movements
WHERE protocol_id = $1 AND is_current = TRUE
ORDER BY sequence DESC LIMIT 1
`

func (q *Queries) GetCurrentMovement(ctx context.Context, protocolID int32) (InternalProtocolMovement, error) {
	row := q.db.QueryRow(ctx, getCurrentMovement, protocolID)
	var i InternalProtocolMovement
	err := row.Scan(
		&i.ID,
		&i.ProtocolID,
		&i.Sequence,
		&i.FromSectorCode,
		&i.FromSectorName,
		&i.ToSectorCode,
		&i.ToSectorName,
		&i.DispatchNote,
		&i.MovedByID,
		&i.MovedByEmail,
		&i.MovedByName,
		&i.MovedAt,
		&i.IsCurrent,
	)
	return i, err
}

const getNextMovementSequence = `-- name: GetNextMovementSequence :one
SELECT COALESCE(MAX(sequence), 0) + 1 AS next_seq
FROM internal_protocol_movements WHERE protocol_id = $1
`

func (q *Queries) GetNextMovementSequence(ctx context.Context, protocolID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getNextMovementSequence, protocolID)
	var next_seq int32
	err := row.Scan(&next_seq)
	return next_seq, err
}

const listMovementsByProtocol = `-- name: ListMovementsByProtocol :many
SELECT id, protocol_id, sequence, from_sector_code, from_sector_name, to_sector_code, to_sector_name, dispatch_note, moved_by_id, moved_by_email, moved_by_name, moved_at, is_current FROM internal_protocol_movements
WHERE protocol_id = $1
ORDER BY sequence DESC
`

func (q *Queries) ListMovementsByProtocol(ctx context.Context, protocolID int32) ([]InternalProtocolMovement, error) {
	rows, err := q.db.Query(ctx, listMovementsByProtocol, protocolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InternalProtocolMovement{}
	for rows.Next() {
		var i InternalProtocolMovement
		if err := rows.Scan(
			&i.ID,
			&i.ProtocolID,
			&i.Sequence,
			&i.FromSectorCode,
			&i.FromSectorName,
			&i.ToSectorCode,
			&i.ToSectorName,
			&i.DispatchNote,
			&i.MovedByID,
			&i.MovedByEmail,
			&i.MovedByName,
			&i.MovedAt,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
