// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID           uuid.UUID        `json:"id"`
	Acao         string           `json:"acao"`
	Entidade     string           `json:"entidade"`
	EntidadeID   pgtype.Text      `json:"entidade_id"`
	Detalhes     json.RawMessage  `json:"detalhes"`
	UsuarioEmail string           `json:"usuario_email"`
	UsuarioNome  string           `json:"usuario_nome"`
	IpAddress    pgtype.Text      `json:"ip_address"`
	CriadoEm     pgtype.Timestamp `json:"criado_em"`
}

type Admin struct {
	ID           uuid.UUID        `json:"id"`
	Email        string           `json:"email"`
	Nome         string           `json:"nome"`
	Role         string           `json:"role"`
	Ativo        pgtype.Bool      `json:"ativo"`
	CriadoPor    pgtype.Text      `json:"criado_por"`
	CriadoEm     pgtype.Timestamp `json:"criado_em"`
	AtualizadoEm pgtype.Timestamp `json:"atualizado_em"`
}

type CacheEmailSetor struct {
	Email        string           `json:"email"`
	Setor        string           `json:"setor"`
	Nome         pgtype.Text      `json:"nome"`
	AtualizadoEm pgtype.Timestamp `json:"atualizado_em"`
}

type Documento struct {
	ID              uuid.UUID        `json:"id"`
	ProtocoloSagi   string           `json:"protocolo_sagi"`
	TipoDocumentoID pgtype.UUID      `json:"tipo_documento_id"`
	NomeArquivo     string           `json:"nome_arquivo"`
	DriveFileID     pgtype.Text      `json:"drive_file_id"`
	DriveFileUrl    pgtype.Text      `json:"drive_file_url"`
	TamanhoBytes    pgtype.Int8      `json:"tamanho_bytes"`
	MimeType        pgtype.Text      `json:"mime_type"`
	HashSha256      pgtype.Text      `json:"hash_sha256"`
	UploadedBy      string           `json:"uploaded_by"`
	UploadedAt      pgtype.Timestamp `json:"uploaded_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
	DeletedBy       pgtype.Text      `json:"deleted_by"`
	MotivoExclusao  pgtype.Text      `json:"motivo_exclusao"`
}

type Observaco struct {
	ID             uuid.UUID        `json:"id"`
	ProtocoloSagi  string           `json:"protocolo_sagi"`
	Texto          string           `json:"texto"`
	AutorEmail     string           `json:"autor_email"`
	AutorNome      string           `json:"autor_nome"`
	CriadoEm       pgtype.Timestamp `json:"criado_em"`
	EditadoEm      pgtype.Timestamp `json:"editado_em"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	DeletedBy      pgtype.Text      `json:"deleted_by"`
	MotivoExclusao pgtype.Text      `json:"motivo_exclusao"`
}

type ProtocolosInterno struct {
	ID             uuid.UUID        `json:"id"`
	Numero         string           `json:"numero"`
	Assunto        string           `json:"assunto"`
	Descricao      pgtype.Text      `json:"descricao"`
	Status         pgtype.Text      `json:"status"`
	SetorOrigem    string           `json:"setor_origem"`
	CriadoPorEmail string           `json:"criado_por_email"`
	CriadoPorNome  string           `json:"criado_por_nome"`
	CriadoEm       pgtype.Timestamp `json:"criado_em"`
	AtualizadoEm   pgtype.Timestamp `json:"atualizado_em"`
}

type TiposDocumento struct {
	ID        uuid.UUID        `json:"id"`
	Nome      string           `json:"nome"`
	Descricao pgtype.Text      `json:"descricao"`
	Ativo     pgtype.Bool      `json:"ativo"`
	CriadoEm  pgtype.Timestamp `json:"criado_em"`
}

type Tramitaco struct {
	ID                 uuid.UUID        `json:"id"`
	ProtocoloInternoID pgtype.UUID      `json:"protocolo_interno_id"`
	DeSetor            string           `json:"de_setor"`
	ParaSetor          string           `json:"para_setor"`
	Despacho           pgtype.Text      `json:"despacho"`
	TramitadoPorEmail  string           `json:"tramitado_por_email"`
	TramitadoPorNome   string           `json:"tramitado_por_nome"`
	TramitadoEm        pgtype.Timestamp `json:"tramitado_em"`
}
