// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: observacoes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createObservacao = `-- name: CreateObservacao :one
INSERT INTO observacoes (protocolo_sagi, texto, autor_email, autor_nome)
VALUES ($1, $2, $3, $4)
RETURNING id, protocolo_sagi, texto, autor_email, autor_nome, criado_em, editado_em, deleted_at, deleted_by, motivo_exclusao
`

type CreateObservacaoParams struct {
	ProtocoloSagi string `json:"protocolo_sagi"`
	Texto         string `json:"texto"`
	AutorEmail    string `json:"autor_email"`
	AutorNome     string `json:"autor_nome"`
}

func (q *Queries) CreateObservacao(ctx context.Context, arg CreateObservacaoParams) (Observaco, error) {
	row := q.db.QueryRow(ctx, createObservacao,
		arg.ProtocoloSagi,
		arg.Texto,
		arg.AutorEmail,
		arg.AutorNome,
	)
	var i Observaco
	err := row.Scan(
		&i.ID,
		&i.ProtocoloSagi,
		&i.Texto,
		&i.AutorEmail,
		&i.AutorNome,
		&i.CriadoEm,
		&i.EditadoEm,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.MotivoExclusao,
	)
	return i, err
}

const listObservacoesByProtocolo = `-- name: ListObservacoesByProtocolo :many
SELECT id, protocolo_sagi, texto, autor_email, autor_nome, criado_em, editado_em, deleted_at, deleted_by, motivo_exclusao FROM observacoes
WHERE protocolo_sagi = $1 AND deleted_at IS NULL
ORDER BY criado_em DESC
`

func (q *Queries) ListObservacoesByProtocolo(ctx context.Context, protocoloSagi string) ([]Observaco, error) {
	rows, err := q.db.Query(ctx, listObservacoesByProtocolo, protocoloSagi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observaco{}
	for rows.Next() {
		var i Observaco
		if err := rows.Scan(
			&i.ID,
			&i.ProtocoloSagi,
			&i.Texto,
			&i.AutorEmail,
			&i.AutorNome,
			&i.CriadoEm,
			&i.EditadoEm,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.MotivoExclusao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteObservacao = `-- name: SoftDeleteObservacao :exec
UPDATE observacoes
SET deleted_at = NOW(), deleted_by = $2, motivo_exclusao = $3
WHERE id = $1
`

type SoftDeleteObservacaoParams struct {
	ID             uuid.UUID   `json:"id"`
	DeletedBy      pgtype.Text `json:"deleted_by"`
	MotivoExclusao pgtype.Text `json:"motivo_exclusao"`
}

func (q *Queries) SoftDeleteObservacao(ctx context.Context, arg SoftDeleteObservacaoParams) error {
	_, err := q.db.Exec(ctx, softDeleteObservacao, arg.ID, arg.DeletedBy, arg.MotivoExclusao)
	return err
}

const updateObservacao = `-- name: UpdateObservacao :exec
UPDATE observacoes SET texto = $2, editado_em = NOW()
WHERE id = $1
`

type UpdateObservacaoParams struct {
	ID    uuid.UUID `json:"id"`
	Texto string    `json:"texto"`
}

func (q *Queries) UpdateObservacao(ctx context.Context, arg UpdateObservacaoParams) error {
	_, err := q.db.Exec(ctx, updateObservacao, arg.ID, arg.Texto)
	return err
}
