// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: protocolos_internos.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProtocoloInterno = `-- name: CreateProtocoloInterno :one
INSERT INTO protocolos_internos (
    numero, assunto, descricao, setor_origem,
    criado_por_email, criado_por_nome
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, numero, assunto, descricao, status, setor_origem, criado_por_email, criado_por_nome, criado_em, atualizado_em
`

type CreateProtocoloInternoParams struct {
	Numero         string      `json:"numero"`
	Assunto        string      `json:"assunto"`
	Descricao      pgtype.Text `json:"descricao"`
	SetorOrigem    string      `json:"setor_origem"`
	CriadoPorEmail string      `json:"criado_por_email"`
	CriadoPorNome  string      `json:"criado_por_nome"`
}

func (q *Queries) CreateProtocoloInterno(ctx context.Context, arg CreateProtocoloInternoParams) (ProtocolosInterno, error) {
	row := q.db.QueryRow(ctx, createProtocoloInterno,
		arg.Numero,
		arg.Assunto,
		arg.Descricao,
		arg.SetorOrigem,
		arg.CriadoPorEmail,
		arg.CriadoPorNome,
	)
	var i ProtocolosInterno
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Assunto,
		&i.Descricao,
		&i.Status,
		&i.SetorOrigem,
		&i.CriadoPorEmail,
		&i.CriadoPorNome,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getNextNumeroProtocolo = `-- name: GetNextNumeroProtocolo :one
SELECT COALESCE(
    MAX(CAST(SPLIT_PART(numero, '-', 3) AS INTEGER)),
    0
) + 1 AS proximo
FROM protocolos_internos
WHERE numero LIKE 'GED-' || TO_CHAR(NOW(), 'YYYY') || '-%'
`

func (q *Queries) GetNextNumeroProtocolo(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextNumeroProtocolo)
	var proximo int32
	err := row.Scan(&proximo)
	return proximo, err
}

const getProtocoloInternoByID = `-- name: GetProtocoloInternoByID :one
SELECT id, numero, assunto, descricao, status, setor_origem, criado_por_email, criado_por_nome, criado_em, atualizado_em FROM protocolos_internos
WHERE id = $1
`

func (q *Queries) GetProtocoloInternoByID(ctx context.Context, id uuid.UUID) (ProtocolosInterno, error) {
	row := q.db.QueryRow(ctx, getProtocoloInternoByID, id)
	var i ProtocolosInterno
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Assunto,
		&i.Descricao,
		&i.Status,
		&i.SetorOrigem,
		&i.CriadoPorEmail,
		&i.CriadoPorNome,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getProtocoloInternoByNumero = `-- name: GetProtocoloInternoByNumero :one
SELECT id, numero, assunto, descricao, status, setor_origem, criado_por_email, criado_por_nome, criado_em, atualizado_em FROM protocolos_internos
WHERE numero = $1
`

func (q *Queries) GetProtocoloInternoByNumero(ctx context.Context, numero string) (ProtocolosInterno, error) {
	row := q.db.QueryRow(ctx, getProtocoloInternoByNumero, numero)
	var i ProtocolosInterno
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Assunto,
		&i.Descricao,
		&i.Status,
		&i.SetorOrigem,
		&i.CriadoPorEmail,
		&i.CriadoPorNome,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listProtocolosInternos = `-- name: ListProtocolosInternos :many
SELECT id, numero, assunto, descricao, status, setor_origem, criado_por_email, criado_por_nome, criado_em, atualizado_em FROM protocolos_internos
WHERE
    ($3::varchar IS NULL OR status = $3)
    AND ($4::varchar IS NULL OR setor_origem = $4)
    AND ($5::varchar IS NULL OR assunto ILIKE '%' || $5 || '%')
ORDER BY criado_em DESC
LIMIT $1 OFFSET $2
`

type ListProtocolosInternosParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	Status      pgtype.Text `json:"status"`
	SetorOrigem pgtype.Text `json:"setor_origem"`
	Busca       pgtype.Text `json:"busca"`
}

func (q *Queries) ListProtocolosInternos(ctx context.Context, arg ListProtocolosInternosParams) ([]ProtocolosInterno, error) {
	rows, err := q.db.Query(ctx, listProtocolosInternos,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.SetorOrigem,
		arg.Busca,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProtocolosInterno{}
	for rows.Next() {
		var i ProtocolosInterno
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.Assunto,
			&i.Descricao,
			&i.Status,
			&i.SetorOrigem,
			&i.CriadoPorEmail,
			&i.CriadoPorNome,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatusProtocoloInterno = `-- name: UpdateStatusProtocoloInterno :exec
UPDATE protocolos_internos
SET status = $2, atualizado_em = NOW()
WHERE id = $1
`

type UpdateStatusProtocoloInternoParams struct {
	ID     uuid.UUID   `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateStatusProtocoloInterno(ctx context.Context, arg UpdateStatusProtocoloInternoParams) error {
	_, err := q.db.Exec(ctx, updateStatusProtocoloInterno, arg.ID, arg.Status)
	return err
}
