// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tipos_documento.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateTipoDocumento = `-- name: ActivateTipoDocumento :exec
UPDATE tipos_documento SET ativo = true
WHERE id = $1
`

func (q *Queries) ActivateTipoDocumento(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, activateTipoDocumento, id)
	return err
}

const createTipoDocumento = `-- name: CreateTipoDocumento :one
INSERT INTO tipos_documento (nome, descricao)
VALUES ($1, $2)
RETURNING id, nome, descricao, ativo, criado_em
`

type CreateTipoDocumentoParams struct {
	Nome      string      `json:"nome"`
	Descricao pgtype.Text `json:"descricao"`
}

func (q *Queries) CreateTipoDocumento(ctx context.Context, arg CreateTipoDocumentoParams) (TiposDocumento, error) {
	row := q.db.QueryRow(ctx, createTipoDocumento, arg.Nome, arg.Descricao)
	var i TiposDocumento
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.Ativo,
		&i.CriadoEm,
	)
	return i, err
}

const deactivateTipoDocumento = `-- name: DeactivateTipoDocumento :exec
UPDATE tipos_documento SET ativo = false
WHERE id = $1
`

func (q *Queries) DeactivateTipoDocumento(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateTipoDocumento, id)
	return err
}

const getTipoDocumentoByID = `-- name: GetTipoDocumentoByID :one
SELECT id, nome, descricao, ativo, criado_em FROM tipos_documento
WHERE id = $1
`

func (q *Queries) GetTipoDocumentoByID(ctx context.Context, id uuid.UUID) (TiposDocumento, error) {
	row := q.db.QueryRow(ctx, getTipoDocumentoByID, id)
	var i TiposDocumento
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.Ativo,
		&i.CriadoEm,
	)
	return i, err
}

const listAllTiposDocumento = `-- name: ListAllTiposDocumento :many
SELECT id, nome, descricao, ativo, criado_em FROM tipos_documento
ORDER BY nome
`

func (q *Queries) ListAllTiposDocumento(ctx context.Context) ([]TiposDocumento, error) {
	rows, err := q.db.Query(ctx, listAllTiposDocumento)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TiposDocumento{}
	for rows.Next() {
		var i TiposDocumento
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Descricao,
			&i.Ativo,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTiposDocumento = `-- name: ListTiposDocumento :many
SELECT id, nome, descricao, ativo, criado_em FROM tipos_documento
WHERE ativo = true
ORDER BY nome
`

func (q *Queries) ListTiposDocumento(ctx context.Context) ([]TiposDocumento, error) {
	rows, err := q.db.Query(ctx, listTiposDocumento)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TiposDocumento{}
	for rows.Next() {
		var i TiposDocumento
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Descricao,
			&i.Ativo,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTipoDocumento = `-- name: UpdateTipoDocumento :exec
UPDATE tipos_documento SET nome = $2, descricao = $3
WHERE id = $1
`

type UpdateTipoDocumentoParams struct {
	ID        uuid.UUID   `json:"id"`
	Nome      string      `json:"nome"`
	Descricao pgtype.Text `json:"descricao"`
}

func (q *Queries) UpdateTipoDocumento(ctx context.Context, arg UpdateTipoDocumentoParams) error {
	_, err := q.db.Exec(ctx, updateTipoDocumento, arg.ID, arg.Nome, arg.Descricao)
	return err
}
