// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tramitacoes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTramitacao = `-- name: CreateTramitacao :one
INSERT INTO tramitacoes (
    protocolo_interno_id, de_setor, para_setor,
    despacho, tramitado_por_email, tramitado_por_nome
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, protocolo_interno_id, de_setor, para_setor, despacho, tramitado_por_email, tramitado_por_nome, tramitado_em
`

type CreateTramitacaoParams struct {
	ProtocoloInternoID pgtype.UUID `json:"protocolo_interno_id"`
	DeSetor            string      `json:"de_setor"`
	ParaSetor          string      `json:"para_setor"`
	Despacho           pgtype.Text `json:"despacho"`
	TramitadoPorEmail  string      `json:"tramitado_por_email"`
	TramitadoPorNome   string      `json:"tramitado_por_nome"`
}

func (q *Queries) CreateTramitacao(ctx context.Context, arg CreateTramitacaoParams) (Tramitaco, error) {
	row := q.db.QueryRow(ctx, createTramitacao,
		arg.ProtocoloInternoID,
		arg.DeSetor,
		arg.ParaSetor,
		arg.Despacho,
		arg.TramitadoPorEmail,
		arg.TramitadoPorNome,
	)
	var i Tramitaco
	err := row.Scan(
		&i.ID,
		&i.ProtocoloInternoID,
		&i.DeSetor,
		&i.ParaSetor,
		&i.Despacho,
		&i.TramitadoPorEmail,
		&i.TramitadoPorNome,
		&i.TramitadoEm,
	)
	return i, err
}

const listTramitacoesByProtocolo = `-- name: ListTramitacoesByProtocolo :many
SELECT id, protocolo_interno_id, de_setor, para_setor, despacho, tramitado_por_email, tramitado_por_nome, tramitado_em FROM tramitacoes
WHERE protocolo_interno_id = $1
ORDER BY tramitado_em DESC
`

func (q *Queries) ListTramitacoesByProtocolo(ctx context.Context, protocoloInternoID pgtype.UUID) ([]Tramitaco, error) {
	rows, err := q.db.Query(ctx, listTramitacoesByProtocolo, protocoloInternoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tramitaco{}
	for rows.Next() {
		var i Tramitaco
		if err := rows.Scan(
			&i.ID,
			&i.ProtocoloInternoID,
			&i.DeSetor,
			&i.ParaSetor,
			&i.Despacho,
			&i.TramitadoPorEmail,
			&i.TramitadoPorNome,
			&i.TramitadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
