// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_recent_protocols.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDocsByProtocoloIDs = `-- name: CountDocsByProtocoloIDs :many
SELECT protocolo_sagi, COUNT(*) AS doc_count
FROM documentos
WHERE protocolo_sagi = ANY($1::varchar[])
  AND deleted_at IS NULL
GROUP BY protocolo_sagi
`

type CountDocsByProtocoloIDsRow struct {
	ProtocoloSagi string `json:"protocolo_sagi"`
	DocCount      int64  `json:"doc_count"`
}

func (q *Queries) CountDocsByProtocoloIDs(ctx context.Context, dollar_1 []string) ([]CountDocsByProtocoloIDsRow, error) {
	rows, err := q.db.Query(ctx, countDocsByProtocoloIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDocsByProtocoloIDsRow{}
	for rows.Next() {
		var i CountDocsByProtocoloIDsRow
		if err := rows.Scan(&i.ProtocoloSagi, &i.DocCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDocsByProtocoloIDsForSetor = `-- name: CountDocsByProtocoloIDsForSetor :one
SELECT COUNT(*)
FROM documentos
WHERE protocolo_sagi = ANY($1::varchar[])
  AND deleted_at IS NULL
`

func (q *Queries) CountDocsByProtocoloIDsForSetor(ctx context.Context, dollar_1 []string) (int64, error) {
	row := q.db.QueryRow(ctx, countDocsByProtocoloIDsForSetor, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocsGlobal = `-- name: CountDocsGlobal :one
SELECT COUNT(*)
FROM documentos
WHERE deleted_at IS NULL
`

func (q *Queries) CountDocsGlobal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDocsGlobal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProtocolosComDocsGlobal = `-- name: CountProtocolosComDocsGlobal :one
SELECT COUNT(DISTINCT protocolo_sagi)
FROM documentos
WHERE deleted_at IS NULL
  AND protocolo_sagi IS NOT NULL
  AND protocolo_sagi != ''
`

func (q *Queries) CountProtocolosComDocsGlobal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProtocolosComDocsGlobal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProtocolosInternos = `-- name: CountProtocolosInternos :one
SELECT COUNT(*)
FROM protocolos_internos
WHERE
    ($1::varchar IS NULL OR status = $1)
    AND ($2::varchar IS NULL OR setor_origem = $2)
    AND ($3::varchar IS NULL OR assunto ILIKE '%' || $3 || '%')
`

type CountProtocolosInternosParams struct {
	Status      pgtype.Text `json:"status"`
	SetorOrigem pgtype.Text `json:"setor_origem"`
	Busca       pgtype.Text `json:"busca"`
}

func (q *Queries) CountProtocolosInternos(ctx context.Context, arg CountProtocolosInternosParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProtocolosInternos, arg.Status, arg.SetorOrigem, arg.Busca)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasRecentObservations = `-- name: HasRecentObservations :many
SELECT protocolo_sagi, COUNT(*) AS obs_count
FROM observacoes
WHERE protocolo_sagi = ANY($1::varchar[])
  AND deleted_at IS NULL
  AND criado_em >= NOW() - INTERVAL '48 hours'
GROUP BY protocolo_sagi
`

type HasRecentObservationsRow struct {
	ProtocoloSagi string `json:"protocolo_sagi"`
	ObsCount      int64  `json:"obs_count"`
}

func (q *Queries) HasRecentObservations(ctx context.Context, dollar_1 []string) ([]HasRecentObservationsRow, error) {
	rows, err := q.db.Query(ctx, hasRecentObservations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HasRecentObservationsRow{}
	for rows.Next() {
		var i HasRecentObservationsRow
		if err := rows.Scan(&i.ProtocoloSagi, &i.ObsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentProtocols = `-- name: ListRecentProtocols :many
SELECT id, user_email, protocol_id, protocol_type, last_viewed_at, view_count FROM user_recent_protocols
WHERE user_email = $1
ORDER BY last_viewed_at DESC
LIMIT $2
`

type ListRecentProtocolsParams struct {
	UserEmail string `json:"user_email"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListRecentProtocols(ctx context.Context, arg ListRecentProtocolsParams) ([]UserRecentProtocol, error) {
	rows, err := q.db.Query(ctx, listRecentProtocols, arg.UserEmail, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRecentProtocol{}
	for rows.Next() {
		var i UserRecentProtocol
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.ProtocolID,
			&i.ProtocolType,
			&i.LastViewedAt,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProtocolosInternos = `-- name: SearchProtocolosInternos :many
SELECT id, numero, assunto, descricao, status, setor_origem, criado_por_email, criado_por_nome, criado_em, atualizado_em
FROM protocolos_internos
WHERE (numero ILIKE '%' || $1 || '%' OR assunto ILIKE '%' || $1 || '%')
ORDER BY criado_em DESC
LIMIT $2
`

type SearchProtocolosInternosParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchProtocolosInternos(ctx context.Context, arg SearchProtocolosInternosParams) ([]ProtocolosInterno, error) {
	rows, err := q.db.Query(ctx, searchProtocolosInternos, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProtocolosInterno{}
	for rows.Next() {
		var i ProtocolosInterno
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.Assunto,
			&i.Descricao,
			&i.Status,
			&i.SetorOrigem,
			&i.CriadoPorEmail,
			&i.CriadoPorNome,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRecentProtocol = `-- name: UpsertRecentProtocol :exec
INSERT INTO user_recent_protocols (user_email, protocol_id, protocol_type, last_viewed_at, view_count)
VALUES ($1, $2, $3, NOW(), 1)
ON CONFLICT (user_email, protocol_id, protocol_type)
DO UPDATE SET last_viewed_at = NOW(), view_count = user_recent_protocols.view_count + 1
`

type UpsertRecentProtocolParams struct {
	UserEmail    string `json:"user_email"`
	ProtocolID   string `json:"protocol_id"`
	ProtocolType string `json:"protocol_type"`
}

func (q *Queries) UpsertRecentProtocol(ctx context.Context, arg UpsertRecentProtocolParams) error {
	_, err := q.db.Exec(ctx, upsertRecentProtocol, arg.UserEmail, arg.ProtocolID, arg.ProtocolType)
	return err
}
